"""Tests for the PATH static GTFS download/cache + parsing.

Two layers, matching the house discipline:
  - Synthetic tables (io.BytesIO / dicts, no disk, no network) exercise the
    pure parsers, the modal shape selection, and the download/cache behavior
    (failure cases point the URL at a closed local port).
  - Golden tests read the committed trimmed copy of the REAL feed under
    fixtures/path_gtfs/ (generated by backend/scripts/gen_path_fixture.py,
    trim rule documented there) and assert the live-verified facts: 13 parent
    stations, 51 child platforms, the 7 routes and their colors, and modal
    shape selection over the real variant spreads. They skip loudly when the
    fixture has not been generated yet; in CI a missing fixture fails instead.
"""

import csv
import io
import os
import time
import zipfile
from collections import Counter, defaultdict
from pathlib import Path

import pytest

import path_static
from conftest import golden_fixture_guard

pytestmark = pytest.mark.anyio

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "path_gtfs"

# Nothing listens here: connection refused, instantly.
DEAD_URL = "http://127.0.0.1:9/path-nj-us.zip"

STOPS_COLS = ["stop_id", "stop_name", "stop_lat", "stop_lon", "location_type", "parent_station"]
TRIPS_COLS = ["route_id", "service_id", "trip_id", "trip_headsign", "direction_id", "shape_id"]
SHAPES_COLS = ["shape_id", "shape_pt_sequence", "shape_pt_lat", "shape_pt_lon"]
STOP_TIMES_COLS = ["trip_id", "stop_id", "stop_sequence"]
ROUTES_COLS = [
    "route_id",
    "route_short_name",
    "route_long_name",
    "route_desc",
    "route_color",
    "route_text_color",
]

# PATH-shaped rows: numeric opaque ids, parent stations (location_type=1) with
# child platforms carrying parent_station.
STOP_ROWS = [
    {
        "stop_id": "26733",
        "stop_name": "Newark",
        "stop_lat": "40.73454",
        "stop_lon": "-74.16375",
        "location_type": "1",
    },
    {
        "stop_id": "26734",
        "stop_name": "World Trade Center",
        "stop_lat": "40.71271",
        "stop_lon": "-74.01193",
        "location_type": "1",
    },
    {
        "stop_id": "781718",
        "stop_name": "Newark Track 1",
        "stop_lat": "40.73454",
        "stop_lon": "-74.16375",
        "location_type": "0",
        "parent_station": "26733",
    },
    {
        "stop_id": "781719",
        "stop_name": "Newark Track 2",
        "stop_lat": "40.73454",
        "stop_lon": "-74.16375",
        "location_type": "",
        "parent_station": "26733",
    },
    {
        "stop_id": "781750",
        "stop_name": "WTC Platform",
        "stop_lat": "",
        "stop_lon": "",
        "location_type": "0",
        "parent_station": "26734",
    },  # child with no usable coords still maps to its parent
]
TRIP_ROWS = [
    {
        "route_id": "862",
        "service_id": "wk",
        "trip_id": "t1",
        "trip_headsign": "World Trade Center",
        "direction_id": "0",
        "shape_id": "nwk_wtc_full",
    },
    {
        "route_id": "862",
        "service_id": "wk",
        "trip_id": "t2",
        "trip_headsign": "",
        "direction_id": "",
        "shape_id": "",
    },  # blank optionals
]
DEFAULT_SHAPE_ROWS = [
    {
        "shape_id": "nwk_wtc_full",
        "shape_pt_sequence": str(i),
        "shape_pt_lat": str(40.70 + i / 100),
        "shape_pt_lon": str(-74.00 - i / 100),
    }
    for i in range(1, 4)
]
ROUTE_ROWS = [
    {
        "route_id": "862",
        "route_long_name": "Newark - World Trade Center",
        # Stale 2020 Sandy-closure text rides on the real 862 row; the parser
        # must never read route_desc, so the tests plant it and assert absence.
        "route_desc": "Suspended due to Superstorm Sandy recovery work",
        "route_color": "d93a30",
        "route_text_color": "ffffff",
    },
    {
        "route_id": "77285",
        "route_short_name": "WTC-33",
        "route_long_name": "",
        "route_color": "65c100",
        "route_text_color": "",
    },
]


def csv_stream(columns, rows) -> io.BytesIO:
    """Render rows as a binary CSV stream, the same shape ZipFile.open yields."""
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=columns)
    writer.writeheader()
    for row in rows:
        writer.writerow({c: row.get(c, "") for c in columns})
    return io.BytesIO(buf.getvalue().encode("utf-8"))


def write_path_zip(
    path,
    stops=STOP_ROWS,
    trips=TRIP_ROWS,
    shapes=DEFAULT_SHAPE_ROWS,
    routes=ROUTE_ROWS,
    stop_times=None,
    members=None,
):
    """Write a minimal PATH GTFS zip; `members` overrides the file map entirely.
    stop_times is optional (13d): most zips in these tests predate the member,
    which is exactly the leniency _parse_zip must keep."""
    if members is None:
        members = {
            "stops.txt": csv_stream(STOPS_COLS, stops).getvalue(),
            "trips.txt": csv_stream(TRIPS_COLS, trips).getvalue(),
            "shapes.txt": csv_stream(SHAPES_COLS, shapes).getvalue(),
            "routes.txt": csv_stream(ROUTES_COLS, routes).getvalue(),
        }
        if stop_times is not None:
            members["stop_times.txt"] = csv_stream(STOP_TIMES_COLS, stop_times).getvalue()
    with zipfile.ZipFile(path, "w") as zf:
        for name, content in members.items():
            zf.writestr(name, content)


@pytest.fixture
def path_paths(tmp_path, monkeypatch):
    """Point the loader at a tmp zip path and a dead URL by default."""
    zip_path = tmp_path / "gtfs_path.zip"
    monkeypatch.setattr(path_static, "PATH_STATIC_ZIP", zip_path)
    monkeypatch.setattr(path_static, "PATH_STATIC_URL", DEAD_URL)
    return zip_path


def age_file(path, days):
    old = time.time() - days * 86400
    os.utime(path, (old, old))


# ---------------- _parse_stops: parent/child split ----------------


def test_parse_stops_splits_parents_from_children():
    parents, child_to_parent = path_static._parse_stops(csv_stream(STOPS_COLS, STOP_ROWS))
    # Parents only in the marker table, values carrying their own id.
    assert set(parents) == {"26733", "26734"}
    assert parents["26733"] == {
        "id": "26733",
        "name": "Newark",
        "lat": 40.73454,
        "lon": -74.16375,
    }
    # Every row with a parent_station maps, even the one with blank coords.
    assert child_to_parent == {
        "781718": "26733",
        "781719": "26733",
        "781750": "26734",
    }


def test_parse_stops_skips_parent_with_malformed_coords():
    rows = STOP_ROWS + [
        {"stop_id": "9999", "stop_name": "Ghost", "stop_lat": "north", "location_type": "1"}
    ]
    parents, _ = path_static._parse_stops(csv_stream(STOPS_COLS, rows))
    assert "9999" not in parents


def test_parse_stops_standalone_platform_is_neither_parent_nor_child():
    rows = [
        {
            "stop_id": "500",
            "stop_name": "Loose Stop",
            "stop_lat": "40.7",
            "stop_lon": "-74.0",
            "location_type": "0",
        }
    ]
    parents, child_to_parent = path_static._parse_stops(csv_stream(STOPS_COLS, rows))
    assert parents == {} and child_to_parent == {}


def test_parse_stops_skips_blank_stop_id():
    rows = [{"stop_id": "", "stop_name": "NoId", "location_type": "1", "parent_station": "1"}]
    parents, child_to_parent = path_static._parse_stops(csv_stream(STOPS_COLS, rows))
    assert parents == {} and child_to_parent == {}


# ---------------- _parse_stop_times + build_path_station_order (13d) ----------------

# Child platform ids resolving to two-plus parents, the real feed's shape:
# stop_times.txt NEVER lists parent ids, so everything below goes through the
# child_to_parent resolution the matcher depends on.
ST_CHILD_TO_PARENT = {
    "781718": "26733",  # Newark platform
    "781719": "26733",
    "781750": "26734",  # World Trade Center platform
    "781730": "26731",  # Journal Square platform
}
# The marker set build_path_station_order filters against (real data keeps
# every child_to_parent target here; the phantom test below drops one).
ST_PARENTS = set(ST_CHILD_TO_PARENT.values())


def st_rows(trip_id, stop_ids, start=1):
    return [
        {"trip_id": trip_id, "stop_id": sid, "stop_sequence": str(start + i)}
        for i, sid in enumerate(stop_ids)
    ]


def test_parse_stop_times_orders_by_sequence_not_file_order():
    rows = [
        {"trip_id": "t1", "stop_id": "781750", "stop_sequence": "3"},
        {"trip_id": "t1", "stop_id": "781718", "stop_sequence": "1"},
        {"trip_id": "t1", "stop_id": "781730", "stop_sequence": "2"},
    ]
    parsed = path_static._parse_stop_times(csv_stream(STOP_TIMES_COLS, rows))
    assert parsed == {"t1": ["781718", "781730", "781750"]}


def test_parse_stop_times_skips_malformed_and_blank_rows():
    rows = [
        {"trip_id": "t1", "stop_id": "781718", "stop_sequence": "1"},
        {"trip_id": "t1", "stop_id": "781730", "stop_sequence": "two"},  # non-integer seq
        {"trip_id": "", "stop_id": "781750", "stop_sequence": "3"},  # blank trip
        {"trip_id": "t1", "stop_id": "", "stop_sequence": "4"},  # blank stop
        {"trip_id": "t1", "stop_id": "781750", "stop_sequence": "5"},
    ]
    parsed = path_static._parse_stop_times(csv_stream(STOP_TIMES_COLS, rows))
    assert parsed == {"t1": ["781718", "781750"]}


def test_parse_stop_times_duplicate_sequence_first_writer_wins():
    rows = [
        {"trip_id": "t1", "stop_id": "781718", "stop_sequence": "1"},
        {"trip_id": "t1", "stop_id": "781750", "stop_sequence": "1"},  # duplicate seq
    ]
    parsed = path_static._parse_stop_times(csv_stream(STOP_TIMES_COLS, rows))
    assert parsed == {"t1": ["781718"]}


ST_TRIPS = {
    "long": {"route_id": "862", "direction_id": "0", "shape_id": "s1", "headsign": None},
    "short": {"route_id": "862", "direction_id": "0", "shape_id": "s2", "headsign": None},
    "back": {"route_id": "862", "direction_id": "1", "shape_id": "s1", "headsign": None},
}


def test_station_order_resolves_child_platforms_to_parents():
    # THE 13d TRAP, pinned: stop_times.txt lists child platform ids (7817xx),
    # never the parent ids (267xx) the realtime bridge uses. An order built
    # without the resolution would contain zero feed-visible ids, so every
    # entry must be a parent id and none may be a child id.
    stop_times = {"long": ["781718", "781730", "781750"]}
    order = path_static.build_path_station_order(
        ST_TRIPS, stop_times, ST_CHILD_TO_PARENT, ST_PARENTS
    )
    assert order == {("862", "0"): ["26733", "26731", "26734"]}
    for stations in order.values():
        assert not any(sid in ST_CHILD_TO_PARENT for sid in stations)  # no child id survives


def test_station_order_longest_trip_wins_per_route_and_direction():
    # The short-turn variant must not define the order: the run with the most
    # stops is the full-length pattern.
    stop_times = {
        "long": ["781718", "781730", "781750"],
        "short": ["781730", "781750"],
        "back": ["781750", "781730", "781718"],
    }
    order = path_static.build_path_station_order(
        ST_TRIPS, stop_times, ST_CHILD_TO_PARENT, ST_PARENTS
    )
    assert order[("862", "0")] == ["26733", "26731", "26734"]  # from "long", not "short"
    assert order[("862", "1")] == ["26734", "26731", "26733"]  # directions stay separate


def test_station_order_length_tie_breaks_to_smallest_trip_id():
    trips = {
        "b": {"route_id": "862", "direction_id": "0", "shape_id": None, "headsign": None},
        "a": {"route_id": "862", "direction_id": "0", "shape_id": None, "headsign": None},
    }
    stop_times = {
        "b": ["781750", "781730"],
        "a": ["781718", "781730"],
    }
    order = path_static.build_path_station_order(trips, stop_times, ST_CHILD_TO_PARENT, ST_PARENTS)
    assert order == {("862", "0"): ["26733", "26731"]}  # trip "a" (smallest id) picked


def test_station_order_drops_unresolvable_entries_and_repeat_visits():
    # An unmapped platform contributes nothing, and a second platform of an
    # already-seen station must not make the station its own predecessor.
    stop_times = {"long": ["781718", "99999", "781719", "781730"]}
    order = path_static.build_path_station_order(
        ST_TRIPS, stop_times, ST_CHILD_TO_PARENT, ST_PARENTS
    )
    assert order == {("862", "0"): ["26733", "26731"]}


def test_station_order_drops_a_phantom_parent_not_in_the_marker_set():
    # The seam a phase-13 review surfaced: a location_type=1 station skipped
    # from the marker set for a malformed coordinate still populates
    # child_to_parent, so without the marker filter it would enter the order
    # as a phantom the realtime feed never places a train at. Dropping it
    # links the phantom's renderable neighbors directly, so the matcher can
    # glide identity ACROSS the unrenderable station instead of resetting at
    # the next real one. Journal Square (26731) is the phantom here.
    stop_times = {"long": ["781718", "781730", "781750"]}  # Newark, JSQ, WTC
    without_jsq = ST_PARENTS - {"26731"}
    order = path_static.build_path_station_order(
        ST_TRIPS, stop_times, ST_CHILD_TO_PARENT, without_jsq
    )
    assert order == {("862", "0"): ["26733", "26734"]}  # Newark -> WTC, JSQ dropped
    # With the full marker set the phantom is a real station and stays.
    full = path_static.build_path_station_order(
        ST_TRIPS, stop_times, ST_CHILD_TO_PARENT, ST_PARENTS
    )
    assert full == {("862", "0"): ["26733", "26731", "26734"]}


def test_station_order_drops_sub_two_station_orders_and_unknown_trips():
    stop_times = {
        "long": ["781718", "781719"],  # both resolve to Newark: 1 station, no edge
        "ghost": ["781718", "781730"],  # trip absent from trips.txt: no route to key by
    }
    order = path_static.build_path_station_order(
        ST_TRIPS, stop_times, ST_CHILD_TO_PARENT, ST_PARENTS
    )
    assert order == {}


# ---------------- derive_path_station_routes (H5) ----------------


def test_derive_path_station_routes_folds_platforms_to_parents():
    # The 13d trap again, from the other direction: stop_times lists child
    # platform ids (7817xx), so the index must be keyed by the PARENT stations
    # (267xx) the markers serve, never the platforms.
    stop_times = {
        "long": ["781718", "781730", "781750"],  # Newark, Journal Sq, WTC on 862
        "back": ["781750", "781718"],  # WTC, Newark on 862 dir 1
    }
    idx = path_static.derive_path_station_routes(ST_TRIPS, stop_times, ST_CHILD_TO_PARENT)
    assert idx == {"26733": ["862"], "26731": ["862"], "26734": ["862"]}
    # No child platform id leaks in as a key.
    assert not (set(idx) & set(ST_CHILD_TO_PARENT))


def test_derive_path_station_routes_unions_and_sorts_routes_per_station():
    trips = {
        "a": {"route_id": "862", "direction_id": "0", "shape_id": None, "headsign": None},
        "b": {"route_id": "861", "direction_id": "0", "shape_id": None, "headsign": None},
    }
    stop_times = {"a": ["781730"], "b": ["781730"]}  # both visit Journal Square (26731)
    idx = path_static.derive_path_station_routes(trips, stop_times, ST_CHILD_TO_PARENT)
    # Two routes serve the one station, de-duplicated and sorted.
    assert idx == {"26731": ["861", "862"]}


def test_derive_path_station_routes_ignores_routeless_trips():
    trips = {"x": {"route_id": None, "direction_id": None, "shape_id": None, "headsign": None}}
    idx = path_static.derive_path_station_routes(trips, {"x": ["781718"]}, ST_CHILD_TO_PARENT)
    assert idx == {}  # a trip with no route says nothing about which route serves a stop


# ---------------- _parse_routes: names + colors, no route_desc ----------------


def test_parse_routes_reads_colors_blank_to_none():
    routes = path_static._parse_routes(csv_stream(ROUTES_COLS, ROUTE_ROWS))
    assert routes["862"] == {
        "long_name": "Newark - World Trade Center",
        "short_name": None,
        "color": "d93a30",
        "text_color": "ffffff",
    }
    assert routes["77285"] == {
        "long_name": None,
        "short_name": "WTC-33",
        "color": "65c100",
        "text_color": None,
    }


def test_parse_routes_never_carries_route_desc():
    # The real 862 row carries stale 2020 Sandy-closure text in route_desc;
    # the parsed table must not have a slot for it to leak through.
    routes = path_static._parse_routes(csv_stream(ROUTES_COLS, ROUTE_ROWS))
    # Exact key set: route_desc (or any other column) can never leak, whatever
    # it is named. The old `"desc" in key` form was dead because _parse_routes
    # hardcodes these four keys, so no key could ever contain "desc".
    assert all(
        set(row) == {"long_name", "short_name", "color", "text_color"} for row in routes.values()
    )
    assert not any("Sandy" in value for row in routes.values() for value in row.values() if value)


def test_parse_routes_skips_blank_id_and_dedups_first_wins():
    rows = [
        {"route_id": "", "route_long_name": "No Id"},
        {"route_id": "859", "route_long_name": "First", "route_color": "4d92fb"},
        {"route_id": "859", "route_long_name": "Second", "route_color": "000000"},
    ]
    routes = path_static._parse_routes(csv_stream(ROUTES_COLS, rows))
    assert set(routes) == {"859"}
    assert routes["859"]["long_name"] == "First" and routes["859"]["color"] == "4d92fb"


# ---------------- _parse_trips / _parse_shapes ----------------


def test_parse_trips_blank_optionals_to_none_and_dedup():
    rows = TRIP_ROWS + [
        {"route_id": "862", "service_id": "wk", "trip_id": "t1", "shape_id": "other"},  # dup
        {"route_id": "859", "service_id": "wk", "trip_id": "", "shape_id": "x"},  # no id
    ]
    trips = path_static._parse_trips(csv_stream(TRIPS_COLS, rows))
    assert set(trips) == {"t1", "t2"}
    assert trips["t1"] == {
        "route_id": "862",
        "direction_id": "0",
        "shape_id": "nwk_wtc_full",
        "headsign": "World Trade Center",
    }  # first writer won over the duplicate
    assert trips["t2"]["direction_id"] is None
    assert trips["t2"]["shape_id"] is None
    assert trips["t2"]["headsign"] is None


def test_parse_shapes_ordered_by_sequence_and_rounded():
    rows = [  # out of order, high precision, plus one malformed row
        {
            "shape_id": "s",
            "shape_pt_sequence": "2",
            "shape_pt_lat": "40.7111149",
            "shape_pt_lon": "-74.0222261",
        },
        {
            "shape_id": "s",
            "shape_pt_sequence": "1",
            "shape_pt_lat": "40.7",
            "shape_pt_lon": "-74.0",
        },
        {
            "shape_id": "BAD",
            "shape_pt_sequence": "x",
            "shape_pt_lat": "40.7",
            "shape_pt_lon": "-74.0",
        },
    ]
    shapes = path_static._parse_shapes(csv_stream(SHAPES_COLS, rows))
    assert shapes["s"] == [[40.7, -74.0], [40.71111, -74.02223]]
    assert "BAD" not in shapes


# ---------------- _parse_zip ----------------


def test_parse_zip_returns_six_tables(tmp_path):
    path = tmp_path / "g.zip"
    write_path_zip(
        path,
        stop_times=[{"trip_id": "t1", "stop_id": "781718", "stop_sequence": "1"}],
    )
    data = path_static._parse_zip(path)
    assert set(data) == {"stops", "child_to_parent", "trips", "shapes", "routes", "stop_times"}
    assert data["stops"]["26734"]["name"] == "World Trade Center"
    assert data["child_to_parent"]["781718"] == "26733"
    assert data["routes"]["862"]["color"] == "d93a30"
    assert data["stop_times"] == {"t1": ["781718"]}


def test_parse_zip_missing_stop_times_degrades_to_empty(tmp_path):
    # A cached zip downloaded before 13d has no stop_times.txt; it must still
    # parse (advance matching just stays disabled) rather than wedging the
    # whole PATH group on an otherwise good cache.
    path = tmp_path / "g.zip"
    write_path_zip(path)
    data = path_static._parse_zip(path)
    assert data["stop_times"] == {}
    assert "26733" in data["stops"] and "t1" in data["trips"]


def test_parse_zip_missing_routes_degrades_to_empty(tmp_path):
    # routes.txt is optional: branding is a rider-facing convenience, not
    # load-critical like stops/trips/shapes.
    path = tmp_path / "g.zip"
    write_path_zip(
        path,
        members={
            "stops.txt": csv_stream(STOPS_COLS, STOP_ROWS).getvalue(),
            "trips.txt": csv_stream(TRIPS_COLS, TRIP_ROWS).getvalue(),
            "shapes.txt": csv_stream(SHAPES_COLS, DEFAULT_SHAPE_ROWS).getvalue(),
        },
    )
    data = path_static._parse_zip(path)
    assert data["routes"] == {}
    assert "26733" in data["stops"] and "t1" in data["trips"]


def test_parse_zip_missing_required_member_raises(tmp_path):
    path = tmp_path / "g.zip"
    write_path_zip(path, members={"agency.txt": "agency_id\nPATH\n"})
    with pytest.raises(KeyError):
        path_static._parse_zip(path)


# ---------------- build_path_route_shapes (synthetic parsed tables) ----------------


def _trip(route_id, shape_id, direction_id="0"):
    return {"route_id": route_id, "shape_id": shape_id, "direction_id": direction_id}


LINE = [[40.70, -74.00], [40.71, -74.01], [40.72, -74.02], [40.73, -74.03]]
SHORT_TURN = LINE[:2]


def test_modal_shape_wins_by_trip_count():
    # Three trips run the full line, one runs a short-turn variant: the modal
    # full line is the route's shape, the variant is dropped (not deduped in).
    shapes = {"full": LINE, "short": SHORT_TURN}
    trips = {
        "a": _trip("862", "full"),
        "b": _trip("862", "full"),
        "c": _trip("862", "full"),
        "d": _trip("862", "short"),
    }
    routes = path_static.build_path_route_shapes(trips, shapes)
    assert len(routes) == 1
    assert routes[0]["id"] == "862"
    assert routes[0]["shape"] == [LINE]


def test_modal_tie_breaks_to_smallest_shape_id():
    # Equal trip counts: the pick must be deterministic across restarts, so the
    # smallest shape_id wins (set/dict iteration order must not decide).
    branch_a = [[41.0, -74.0], [41.1, -74.1], [41.2, -74.2]]
    branch_z = [[42.0, -74.0], [42.1, -74.1], [42.2, -74.2]]
    shapes = {"a_shape": branch_a, "z_shape": branch_z}
    trips = {"t1": _trip("861", "z_shape"), "t2": _trip("861", "a_shape")}
    routes = path_static.build_path_route_shapes(trips, shapes)
    assert routes[0]["shape"] == [branch_a]


def test_modal_selected_per_direction_and_reverse_collapses():
    # Direction 1's modal is the same line reversed: the point-set dedup reads
    # it as 0% new and collapses it, leaving one rider-facing polyline.
    shapes = {"fwd": LINE, "rev": list(reversed(LINE))}
    trips = {
        "t1": _trip("860", "fwd", "0"),
        "t2": _trip("860", "fwd", "0"),
        "t3": _trip("860", "rev", "1"),
        "t4": _trip("860", "rev", "1"),
    }
    routes = path_static.build_path_route_shapes(trips, shapes)
    assert routes[0]["shape"] == [LINE]


def test_modal_divergent_direction_survives():
    # A direction whose modal genuinely diverges (a different alignment, not a
    # reversal) adds geometry and is kept alongside the other direction's line.
    other = [[45.0, -74.0], [45.1, -74.1], [45.2, -74.2], [45.3, -74.3], [45.4, -74.4]]
    shapes = {"fwd": LINE, "diverged": other}
    trips = {"t1": _trip("1024", "fwd", "0"), "t2": _trip("1024", "diverged", "1")}
    routes = path_static.build_path_route_shapes(trips, shapes)
    # Longest first (the dedup keeps the fullest line first).
    assert routes[0]["shape"] == [other, LINE]


def test_modal_counts_do_not_leak_across_directions():
    # Direction 0 runs the short variant twice, direction 1 runs the full line
    # once. If counts pooled across directions the short would win overall; per
    # direction each is modal in its own group, and the dedup then keeps the
    # full line plus nothing new from the short (a strict subset).
    shapes = {"full": LINE, "short": SHORT_TURN}
    trips = {
        "t1": _trip("859", "short", "0"),
        "t2": _trip("859", "short", "0"),
        "t3": _trip("859", "full", "1"),
    }
    routes = path_static.build_path_route_shapes(trips, shapes)
    assert routes[0]["shape"] == [LINE]  # short is a subset: collapses into full


def test_blank_direction_is_its_own_group():
    shapes = {"full": LINE}
    trips = {"t1": {"route_id": "859", "shape_id": "full", "direction_id": None}}
    routes = path_static.build_path_route_shapes(trips, shapes)
    assert routes[0]["shape"] == [LINE]


def test_route_without_usable_geometry_dropped():
    shapes = {"deg": [[40.7, -74.0]]}  # single point: degenerate
    trips = {
        "t1": _trip("859", "deg"),
        "t2": _trip("859", "missing_shape"),
        "t3": _trip("860", ""),
        "t4": {"route_id": "861", "shape_id": None, "direction_id": None},
    }
    assert path_static.build_path_route_shapes(trips, shapes) == []


def test_route_branding_carried_and_output_sorted():
    shapes = {"s1": LINE, "s2": [[41.0, -74.0], [41.1, -74.1]]}
    trips = {"t1": _trip("862", "s1"), "t2": _trip("1024", "s2")}
    routes_table = {
        "862": {
            "long_name": "Newark - World Trade Center",
            "short_name": None,
            "color": "d93a30",
            "text_color": "ffffff",
        },
        # 1024 absent from routes.txt: branding degrades to nulls, geometry kept.
    }
    routes = path_static.build_path_route_shapes(trips, shapes, routes_table)
    assert [r["id"] for r in routes] == ["1024", "862"]  # sorted by route id
    assert routes[0] == {
        "id": "1024",
        "name": None,
        "color": None,
        "text_color": None,
        "shape": [shapes["s2"]],
    }
    assert routes[1]["name"] == "Newark - World Trade Center"
    assert routes[1]["color"] == "d93a30"
    assert routes[1]["text_color"] == "ffffff"


def test_short_name_fallback_when_no_long_name():
    shapes = {"s": LINE}
    trips = {"t1": _trip("77285", "s")}
    routes_table = {"77285": {"long_name": None, "short_name": "WTC-33", "color": None}}
    routes = path_static.build_path_route_shapes(trips, shapes, routes_table)
    assert routes[0]["name"] == "WTC-33"


# ---------------- load_path_static: download/cache behavior ----------------


async def test_fresh_cache_parsed_without_downloading(path_paths, monkeypatch):
    write_path_zip(path_paths)

    async def fail():  # any download attempt is a test failure
        raise AssertionError("should not download with a fresh cache")

    monkeypatch.setattr(path_static, "_download_zip", fail)
    data = await path_static.load_path_static()
    assert data["stops"]["26733"]["name"] == "Newark"
    assert data["child_to_parent"]["781750"] == "26734"


async def test_stale_cache_with_failed_download_falls_back(path_paths):
    write_path_zip(path_paths)
    age_file(path_paths, days=40)  # past MAX_AGE_DAYS; the dead URL fails fast
    data = await path_static.load_path_static()
    assert data and "26733" in data["stops"]


async def test_missing_cache_with_failed_download_returns_empty(path_paths):
    # Lenient failure, matching load_railroad_static: no cache and a dead URL
    # yield an EMPTY result, never an exception (the warmup owns retrying).
    assert not path_paths.exists()
    data = await path_static.load_path_static()
    assert data == {}


@pytest.mark.parametrize(
    "make_bad_cache",
    [
        lambda path: path.write_bytes(b"this is not a zip archive"),
        lambda path: write_path_zip(path, members={"agency.txt": "agency_id\nPATH\n"}),
    ],
    ids=["corrupt-zip", "zip-missing-stops.txt"],
)
async def test_unusable_fresh_cache_redownloads_exactly_once(
    path_paths, monkeypatch, make_bad_cache
):
    make_bad_cache(path_paths)  # fresh mtime; only the recovery download should fire
    calls = []

    async def fake_download():
        calls.append(True)
        write_path_zip(path_paths)

    monkeypatch.setattr(path_static, "_download_zip", fake_download)
    data = await path_static.load_path_static()
    assert calls == [True]  # exactly one re-download
    assert "26733" in data["stops"]


async def test_unusable_cache_and_failed_redownload_returns_empty(path_paths):
    path_paths.write_bytes(b"this is not a zip archive")  # fresh mtime, dead URL
    data = await path_static.load_path_static()
    assert data == {}


# A structurally valid zip whose stops.txt has NO parent stations (only child
# platforms): _parse_zip succeeds but data["stops"] is empty. This is the
# "fresh-but-empty cache" the loader must not wedge on.
EMPTY_PARENT_STOPS = [
    {
        "stop_id": "781718",
        "stop_name": "Newark Track 1",
        "stop_lat": "40.73454",
        "stop_lon": "-74.16375",
        "location_type": "0",
        "parent_station": "26733",
    }
]


async def test_fresh_but_empty_cache_redownloads_and_recovers(path_paths, monkeypatch):
    # A fresh cache that parses to ZERO parent stations is treated as unusable,
    # so the loader re-downloads once instead of trusting the fresh mtime and
    # wedging until MAX_AGE_DAYS. Without this a transiently-empty upstream would
    # never be refetched even after it self-corrected.
    write_path_zip(path_paths, stops=EMPTY_PARENT_STOPS)  # fresh, valid, no parents
    calls = []

    async def fake_download():
        calls.append(True)
        write_path_zip(path_paths)  # upstream corrected: now has parent stations

    monkeypatch.setattr(path_static, "_download_zip", fake_download)
    data = await path_static.load_path_static()
    assert calls == [True]  # exactly one recovery download
    assert "26733" in data["stops"]  # the corrected feed is picked up


async def test_persistently_empty_feed_returns_empty(path_paths):
    # Fresh empty cache + a dead URL: the recovery re-download also fails, so the
    # result is {} and the warmup marks the group failed (single-system PATH). The
    # cache invalidation still fired, so the NEXT warm retry re-downloads again.
    write_path_zip(path_paths, stops=EMPTY_PARENT_STOPS)  # fresh, valid, no parents
    data = await path_static.load_path_static()
    assert data == {}


# ---------------- golden tests over the trimmed real fixture ----------------
#
# fixtures/path_gtfs/ is a trimmed copy of the real Trillium feed written by
# backend/scripts/gen_path_fixture.py (trim rule documented there: stops and
# routes in full, trips cut to 3 modal + 1 per variant shape per (route,
# direction), shapes cut to the referenced ids). These tests skip until the
# fixture is generated, which needs egress to data.trilliumtransit.com. In CI
# a missing fixture fails instead; see conftest.golden_fixture_guard.

golden = golden_fixture_guard(FIXTURE_DIR / "stops.txt", "backend/scripts/gen_path_fixture.py")

EXPECTED_ROUTE_COLORS = {
    "859": "4d92fb",  # Hoboken - 33rd
    "860": "65c100",  # Hoboken - WTC
    "861": "ff9900",  # Journal Square - 33rd
    "862": "d93a30",  # Newark - WTC
    "1024": "ff9900",  # Journal Square - 33rd via Hoboken
    "74320": "8c3c96",  # Newark - Harrison Shuttle
    "77285": "65c100",  # WTC - 33rd
}


def _fixture(name):
    return io.BytesIO((FIXTURE_DIR / name).read_bytes())


@golden
def test_golden_parent_child_split_matches_live_feed():
    parents, child_to_parent = path_static._parse_stops(_fixture("stops.txt"))
    # Untrimmed counts (stops.txt is committed in full): 13 parent stations
    # and 51 child platforms, verified live 2026-07-05.
    assert len(parents) == 13
    assert len(child_to_parent) == 51
    assert parents["26733"]["name"] == "Newark"
    assert parents["26734"]["name"] == "World Trade Center"
    # Every child maps to a real parent, and no parent is its own child.
    assert set(child_to_parent.values()) <= set(parents)
    assert not (set(child_to_parent) & set(parents))


@golden
def test_golden_route_table_colors():
    routes = path_static._parse_routes(_fixture("routes.txt"))
    assert {rid: r["color"] for rid, r in routes.items()} == EXPECTED_ROUTE_COLORS
    assert all(r["text_color"] for r in routes.values())
    # Exact key set, so the stale route_desc on 862 cannot leak (any name).
    assert all(
        set(r) == {"long_name", "short_name", "color", "text_color"} for r in routes.values()
    )


@golden
def test_golden_every_trip_shape_resolves():
    trips = path_static._parse_trips(_fixture("trips.txt"))
    shapes = path_static._parse_shapes(_fixture("shapes.txt"))
    referenced = {t["shape_id"] for t in trips.values() if t["shape_id"]}
    assert referenced and referenced <= set(shapes)


@golden
def test_golden_route_shapes_are_the_modal_picks():
    trips = path_static._parse_trips(_fixture("trips.txt"))
    shapes = path_static._parse_shapes(_fixture("shapes.txt"))
    routes_table = path_static._parse_routes(_fixture("routes.txt"))
    built = path_static.build_path_route_shapes(trips, shapes, routes_table)

    # All 7 routes carry usable geometry (verified per route on the live feed).
    assert [r["id"] for r in built] == sorted(EXPECTED_ROUTE_COLORS)
    for entry in built:
        assert entry["color"] == EXPECTED_ROUTE_COLORS[entry["id"]]
        assert entry["name"]

    # Recompute the modal picks independently (most trips per (route,
    # direction), ties to the smallest shape_id) and require every served
    # polyline to BE one of its route's modal shapes: the variant short-turn /
    # track-work shapes must never leak into the output.
    counts = defaultdict(lambda: defaultdict(Counter))
    for t in trips.values():
        if t["route_id"] and t["shape_id"]:
            counts[t["route_id"]][t["direction_id"]][t["shape_id"]] += 1
    for entry in built:
        modal_polylines = []
        for tally in counts[entry["id"]].values():
            shape_id = min(tally, key=lambda s: (-tally[s], s))
            modal_polylines.append(shapes[shape_id])
        for polyline in entry["shape"]:
            assert polyline in modal_polylines


@golden
def test_golden_modal_spread_is_exercised():
    # The trim keeps every variant shape id, so the fixture still carries the
    # real spread that makes modal selection matter: 1024 references 18 shape
    # ids and 862 references 10 (live-verified counts).
    trips = path_static._parse_trips(_fixture("trips.txt"))
    by_route = defaultdict(set)
    for t in trips.values():
        if t["route_id"] and t["shape_id"]:
            by_route[t["route_id"]].add(t["shape_id"])
    assert len(by_route["1024"]) == 18
    assert len(by_route["862"]) == 10


# ---------------- goldens over the trimmed stop_times (13d) ----------------
#
# stop_times.txt joins the committed fixture in 13d (gen_path_fixture.py trims
# it to the kept trips and verifies the trimmed tables reproduce the full
# feed's station orders before writing). Gated on its own guard because the
# 13a fixture files can exist without it (a pre-13d checkout regenerated only
# four tables); in CI a missing member fails instead of skipping.

golden_stop_times = golden_fixture_guard(
    FIXTURE_DIR / "stop_times.txt", "backend/scripts/gen_path_fixture.py"
)


@golden_stop_times
def test_golden_station_order_matches_live_verified_862_sequence():
    parents, child_to_parent = path_static._parse_stops(_fixture("stops.txt"))
    trips = path_static._parse_trips(_fixture("trips.txt"))
    stop_times = path_static._parse_stop_times(_fixture("stop_times.txt"))
    order = path_static.build_path_station_order(trips, stop_times, child_to_parent, parents)
    # Route 862 direction 0 (New Jersey-bound), verified live 2026-07-07: the
    # sequence the advance matcher walks for the Newark - World Trade Center line.
    names = [parents[sid]["name"] for sid in order[("862", "0")]]
    assert names == [
        "World Trade Center",
        "Exchange Place",
        "Grove Street",
        "Journal Square",
        "Harrison",
        "Newark",
    ]


@golden_stop_times
def test_golden_station_orders_are_feed_visible_parent_ids():
    # THE TRAP, against the real tables: stop_times.txt carries child platform
    # ids, and an order built without child_to_parent resolution would contain
    # zero ids the realtime bridge ever references. Every entry must be a
    # known parent station and never a child platform id.
    parents, child_to_parent = path_static._parse_stops(_fixture("stops.txt"))
    trips = path_static._parse_trips(_fixture("trips.txt"))
    stop_times = path_static._parse_stop_times(_fixture("stop_times.txt"))
    order = path_static.build_path_station_order(trips, stop_times, child_to_parent, parents)
    assert order  # at least one (route, direction) produced a walkable order
    for (route_id, direction_id), stations in order.items():
        assert len(stations) >= 2
        assert all(sid in parents for sid in stations)
        assert not any(sid in child_to_parent for sid in stations)


@golden_stop_times
def test_golden_routes_per_station_matches_live_feed():
    # H5 routes-per-station index over the real trim: every one of the 13 parent
    # stations is served by at least one route, the index is keyed by parent
    # ids (never child platforms), and the exact route sets are the ones the
    # live feed produced (verified 2026-07-07). WTC and Newark are the Newark -
    # WTC line's endpoints; the Sixth-Avenue Manhattan stations share the same
    # four Hudson-crossing routes.
    parents, child_to_parent = path_static._parse_stops(_fixture("stops.txt"))
    trips = path_static._parse_trips(_fixture("trips.txt"))
    stop_times = path_static._parse_stop_times(_fixture("stop_times.txt"))
    idx = path_static.derive_path_station_routes(trips, stop_times, child_to_parent)
    assert set(idx) == set(parents)  # every station served
    assert set(idx) <= set(parents) and not (set(idx) & set(child_to_parent))
    assert idx["26733"] == ["74320", "862"]  # Newark: WTC line + Harrison shuttle
    assert idx["26734"] == ["77285", "860", "862"]  # World Trade Center
    assert idx["26731"] == ["1024", "861", "862"]  # Journal Square
    # Every route id in the index is a real route in routes.txt.
    routes_table = path_static._parse_routes(_fixture("routes.txt"))
    assert {r for served in idx.values() for r in served} <= set(routes_table)
