"""Tests for the NYC Ferry static GTFS download/cache + parsing.

Two layers, matching test_path_static.py's house discipline:
  - Synthetic tables (io.BytesIO / dicts, no disk, no network) exercise the
    pure parsers, the modal shape selection, and the download/cache behavior
    (failure cases point the URL at a closed local port; the redirect-follow
    path uses a tiny in-process http server).
  - Golden tests read the committed trimmed copy of the REAL feed under
    fixtures/ferry_gtfs/ (generated by backend/scripts/gen_ferry_fixture.py,
    trim rule documented there) and assert the live-verified facts: 50 stops,
    the 9 routes and their colors and names, modal shape selection over the
    real variant spreads, and the trip -> route map. They skip loudly when the
    fixture has not been generated yet; in CI a missing fixture fails instead.
"""

import csv
import http.server
import io
import os
import threading
import time
import zipfile
from collections import defaultdict
from pathlib import Path

import pytest

import ferry_static
from conftest import golden_fixture_guard

pytestmark = pytest.mark.anyio

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "ferry_gtfs"

# Nothing listens here: connection refused, instantly.
DEAD_URL = "http://127.0.0.1:9/gtfs.aspx"

STOPS_COLS = ["stop_id", "stop_name", "stop_lat", "stop_lon", "wheelchair_boarding"]
TRIPS_COLS = ["route_id", "service_id", "trip_id", "trip_headsign", "direction_id", "shape_id"]
SHAPES_COLS = ["shape_id", "shape_pt_sequence", "shape_pt_lat", "shape_pt_lon"]
ROUTES_COLS = [
    "route_id",
    "route_short_name",
    "route_long_name",
    "route_type",
    "route_color",
    "route_text_color",
]

# Ferry-shaped rows: short numeric ids, FLAT stops (no location_type, no
# parent_station), wheelchair_boarding 1 or blank.
STOP_ROWS = [
    {
        "stop_id": "18",
        "stop_name": "Wall St/Pier 11",
        "stop_lat": "40.70355",
        "stop_lon": "-74.00512",
        "wheelchair_boarding": "1",
    },
    {
        "stop_id": "2",
        "stop_name": "ER01 - South Williamsburg",
        "stop_lat": "40.70951",
        "stop_lon": "-73.96769",
        "wheelchair_boarding": "",  # blank: no affirmative accessibility info
    },
    {
        "stop_id": "113",
        "stop_name": "No Coords",
        "stop_lat": "",
        "stop_lon": "",
        "wheelchair_boarding": "1",
    },  # malformed coord: skipped
]
TRIP_ROWS = [
    {
        "route_id": "ER",
        "service_id": "wk",
        "trip_id": "t1",
        "trip_headsign": "Wall St/Pier 11",
        "direction_id": "0",
        "shape_id": "er_full",
    },
    {
        "route_id": "AS",
        "service_id": "wk",
        "trip_id": "t2",
        "trip_headsign": "",
        "direction_id": "",
        "shape_id": "",
    },  # blank optionals
]
DEFAULT_SHAPE_ROWS = [
    {
        "shape_id": "er_full",
        "shape_pt_sequence": str(i),
        "shape_pt_lat": str(40.70 + i / 100),
        "shape_pt_lon": str(-73.96 - i / 100),
    }
    for i in range(1, 4)
]
ROUTE_ROWS = [
    {
        "route_id": "ER",
        "route_long_name": "East River",
        "route_type": "4",
        "route_color": "00839C",
        "route_text_color": "FFFFFF",
    },
    {
        "route_id": "AS",
        "route_short_name": "AST",
        "route_long_name": "",
        "route_type": "4",
        "route_color": "FF6B00",
        "route_text_color": "",
    },
]


def csv_stream(columns, rows) -> io.BytesIO:
    """Render rows as a binary CSV stream, the same shape ZipFile.open yields."""
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=columns)
    writer.writeheader()
    for row in rows:
        writer.writerow({c: row.get(c, "") for c in columns})
    return io.BytesIO(buf.getvalue().encode("utf-8"))


def _zip_bytes(
    stops=STOP_ROWS, trips=TRIP_ROWS, shapes=DEFAULT_SHAPE_ROWS, routes=ROUTE_ROWS, members=None
):
    """Return a NYC Ferry GTFS zip as bytes; `members` overrides the file map."""
    if members is None:
        members = {
            "stops.txt": csv_stream(STOPS_COLS, stops).getvalue(),
            "trips.txt": csv_stream(TRIPS_COLS, trips).getvalue(),
            "shapes.txt": csv_stream(SHAPES_COLS, shapes).getvalue(),
            "routes.txt": csv_stream(ROUTES_COLS, routes).getvalue(),
        }
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for name, content in members.items():
            zf.writestr(name, content)
    return buf.getvalue()


def write_ferry_zip(path, **kwargs):
    path.write_bytes(_zip_bytes(**kwargs))


@pytest.fixture
def ferry_paths(tmp_path, monkeypatch):
    """Point the loader at a tmp zip path and a dead URL by default."""
    zip_path = tmp_path / "gtfs_ferry.zip"
    monkeypatch.setattr(ferry_static, "FERRY_STATIC_ZIP", zip_path)
    monkeypatch.setattr(ferry_static, "FERRY_STATIC_URL", DEAD_URL)
    return zip_path


def age_file(path, days):
    old = time.time() - days * 86400
    os.utime(path, (old, old))


# ---------------- _parse_stops: flat markers, wheelchair passthrough ----------------


def test_parse_stops_flat_with_wheelchair_passthrough():
    stops = ferry_static._parse_stops(csv_stream(STOPS_COLS, STOP_ROWS))
    # Every row with a usable id and coordinate is a marker (no parent/child).
    assert set(stops) == {"18", "2"}
    assert stops["18"] == {
        "id": "18",
        "name": "Wall St/Pier 11",
        "lat": 40.70355,
        "lon": -74.00512,
        "wheelchair": True,
    }
    # Blank wheelchair_boarding reads as no affirmative info (False).
    assert stops["2"]["wheelchair"] is False


def test_parse_stops_skips_malformed_coords_and_blank_ids():
    rows = STOP_ROWS + [
        {"stop_id": "", "stop_name": "NoId", "stop_lat": "40.7", "stop_lon": "-74.0"},
        {"stop_id": "9", "stop_name": "BadLat", "stop_lat": "north", "stop_lon": "-74.0"},
    ]
    stops = ferry_static._parse_stops(csv_stream(STOPS_COLS, rows))
    assert set(stops) == {"18", "2"}  # 113 (no coords), blank id, and bad-lat all skipped


def test_parse_stops_first_writer_wins_on_duplicate_id():
    rows = [
        {"stop_id": "5", "stop_name": "First", "stop_lat": "40.7", "stop_lon": "-74.0"},
        {"stop_id": "5", "stop_name": "Second", "stop_lat": "40.8", "stop_lon": "-74.1"},
    ]
    stops = ferry_static._parse_stops(csv_stream(STOPS_COLS, rows))
    assert stops["5"]["name"] == "First"


def test_parse_stops_wheelchair_only_1_is_accessible():
    rows = [
        {
            "stop_id": "a",
            "stop_name": "A",
            "stop_lat": "40.7",
            "stop_lon": "-74.0",
            "wheelchair_boarding": "1",
        },
        {
            "stop_id": "b",
            "stop_name": "B",
            "stop_lat": "40.7",
            "stop_lon": "-74.0",
            "wheelchair_boarding": "2",
        },
        {
            "stop_id": "c",
            "stop_name": "C",
            "stop_lat": "40.7",
            "stop_lon": "-74.0",
            "wheelchair_boarding": "0",
        },
    ]
    stops = ferry_static._parse_stops(csv_stream(STOPS_COLS, rows))
    # GTFS: 1 = accessible; 0/2/blank = no affirmative info. Only "1" -> True.
    assert (stops["a"]["wheelchair"], stops["b"]["wheelchair"], stops["c"]["wheelchair"]) == (
        True,
        False,
        False,
    )


# ---------------- _parse_routes: names + colors ----------------


def test_parse_routes_reads_names_and_colors_blank_to_none():
    routes = ferry_static._parse_routes(csv_stream(ROUTES_COLS, ROUTE_ROWS))
    assert routes["ER"] == {
        "long_name": "East River",
        "short_name": None,
        "color": "00839C",
        "text_color": "FFFFFF",
    }
    # AS has a short_name but a blank long_name and blank text_color.
    assert routes["AS"]["short_name"] == "AST"
    assert routes["AS"]["long_name"] is None
    assert routes["AS"]["text_color"] is None


def test_parse_routes_skips_blank_id_and_dedups_first_wins():
    rows = [
        {"route_id": "", "route_long_name": "No Id"},
        {"route_id": "SB", "route_long_name": "South Brooklyn", "route_color": "FFD100"},
        {"route_id": "SB", "route_long_name": "Second", "route_color": "000000"},
    ]
    routes = ferry_static._parse_routes(csv_stream(ROUTES_COLS, rows))
    assert set(routes) == {"SB"}
    assert routes["SB"]["long_name"] == "South Brooklyn"  # first-writer-wins


# ---------------- _parse_trips: trip -> route (the 14b join key) ----------------


def test_parse_trips_keys_trip_to_route_and_shape():
    trips = ferry_static._parse_trips(csv_stream(TRIPS_COLS, TRIP_ROWS))
    assert trips["t1"] == {
        "route_id": "ER",
        "direction_id": "0",
        "shape_id": "er_full",
        "headsign": "Wall St/Pier 11",
    }
    # Blank optionals become None; the trip still resolves to its route.
    assert trips["t2"]["route_id"] == "AS"
    assert trips["t2"]["direction_id"] is None and trips["t2"]["shape_id"] is None


def test_parse_trips_skips_blank_id_first_writer_wins():
    rows = [
        {"route_id": "ER", "trip_id": "", "shape_id": "x"},
        {"route_id": "ER", "trip_id": "t", "shape_id": "a"},
        {"route_id": "AS", "trip_id": "t", "shape_id": "b"},
    ]
    trips = ferry_static._parse_trips(csv_stream(TRIPS_COLS, rows))
    assert set(trips) == {"t"}
    assert trips["t"]["route_id"] == "ER"  # first-writer-wins


# ---------------- _parse_shapes ----------------


def test_parse_shapes_orders_by_sequence_and_rounds():
    rows = [
        {
            "shape_id": "s",
            "shape_pt_sequence": "3",
            "shape_pt_lat": "40.700003",
            "shape_pt_lon": "-74.0",
        },
        {
            "shape_id": "s",
            "shape_pt_sequence": "1",
            "shape_pt_lat": "40.711119",
            "shape_pt_lon": "-74.01",
        },
    ]
    shapes = ferry_static._parse_shapes(csv_stream(SHAPES_COLS, rows))
    assert shapes["s"] == [[40.71112, -74.01], [40.7, -74.0]]  # seq order, 5-dp rounding


def test_parse_shapes_skips_malformed_without_empty_entry():
    rows = [
        {
            "shape_id": "s",
            "shape_pt_sequence": "one",
            "shape_pt_lat": "40.7",
            "shape_pt_lon": "-74.0",
        },
        {"shape_id": "", "shape_pt_sequence": "1", "shape_pt_lat": "40.7", "shape_pt_lon": "-74.0"},
    ]
    shapes = ferry_static._parse_shapes(csv_stream(SHAPES_COLS, rows))
    assert shapes == {}  # a malformed-only shape never materializes an empty list


# ---------------- build_ferry_route_shapes: modal selection ----------------


def _trip(route, direction, shape):
    return {"route_id": route, "direction_id": direction, "shape_id": shape, "headsign": None}


def test_route_shapes_picks_modal_shape_per_direction():
    # ER dir 0 has shapes a (2 trips) and b (1 trip); modal is a.
    trips = {
        "1": _trip("ER", "0", "a"),
        "2": _trip("ER", "0", "a"),
        "3": _trip("ER", "0", "b"),
    }
    shapes = {"a": [[0, 0], [1, 1], [2, 2]], "b": [[9, 9], [8, 8]]}
    routes = {
        "ER": {
            "long_name": "East River",
            "short_name": None,
            "color": "00839C",
            "text_color": "FFF",
        }
    }
    built = ferry_static.build_ferry_route_shapes(trips, shapes, routes)
    assert len(built) == 1
    entry = built[0]
    assert entry["id"] == "ER" and entry["name"] == "East River" and entry["color"] == "00839C"
    assert entry["shape"] == [shapes["a"]]  # modal shape a, not the minority b


def test_route_shapes_tie_breaks_to_smallest_shape_id():
    trips = {"1": _trip("AS", "0", "z"), "2": _trip("AS", "0", "a")}  # 1 each: tie
    shapes = {"z": [[0, 0], [1, 1]], "a": [[5, 5], [6, 6]]}
    built = ferry_static.build_ferry_route_shapes(trips, shapes, {})
    assert built[0]["shape"] == [shapes["a"]]  # smallest shape_id wins the tie


def test_route_shapes_dedups_reverse_direction_keeps_divergent():
    # dir 0 and dir 1 share the same point set (reverse order): collapse to one.
    fwd = [[0, 0], [1, 1], [2, 2]]
    rev = [[2, 2], [1, 1], [0, 0]]
    trips = {"1": _trip("ER", "0", "f"), "2": _trip("ER", "1", "r")}
    built = ferry_static.build_ferry_route_shapes(trips, {"f": fwd, "r": rev}, {})
    assert len(built[0]["shape"]) == 1  # reverse collapses

    # A genuinely divergent second direction survives.
    other = [[10, 10], [11, 11], [12, 12]]
    trips2 = {"1": _trip("SB", "0", "f"), "2": _trip("SB", "1", "o")}
    built2 = ferry_static.build_ferry_route_shapes(trips2, {"f": fwd, "o": other}, {})
    assert len(built2[0]["shape"]) == 2


def test_route_shapes_drops_route_with_only_degenerate_shapes():
    trips = {"1": _trip("GI", "0", "pt")}
    built = ferry_static.build_ferry_route_shapes(trips, {"pt": [[0, 0]]}, {})  # single point
    assert built == []


# ---------------- download / cache behavior ----------------


async def test_fresh_cache_parsed_without_downloading(ferry_paths, monkeypatch):
    write_ferry_zip(ferry_paths)

    async def fail():
        raise AssertionError("should not download with a fresh cache")

    monkeypatch.setattr(ferry_static, "_download_zip", fail)
    data = await ferry_static.load_ferry_static()
    assert data["stops"]["18"]["name"] == "Wall St/Pier 11"
    assert data["trips"]["t1"]["route_id"] == "ER"


async def test_stale_cache_with_failed_download_falls_back(ferry_paths):
    write_ferry_zip(ferry_paths)
    age_file(ferry_paths, days=40)  # past MAX_AGE_DAYS; the dead URL fails fast
    data = await ferry_static.load_ferry_static()
    assert data and "18" in data["stops"]  # stale cache still serves


async def test_missing_cache_with_failed_download_returns_empty(ferry_paths):
    # Lenient failure: no cache and a dead URL yield an EMPTY result, never an
    # exception (the warmup owns retrying).
    assert not ferry_paths.exists()
    data = await ferry_static.load_ferry_static()
    assert data == {}


@pytest.mark.parametrize(
    "make_bad_cache",
    [
        lambda path: path.write_bytes(b"this is not a zip archive"),
        lambda path: write_ferry_zip(path, members={"agency.txt": "agency_id\nNYCF\n"}),
    ],
    ids=["corrupt-zip", "zip-missing-stops.txt"],
)
async def test_unusable_fresh_cache_redownloads_exactly_once(
    ferry_paths, monkeypatch, make_bad_cache
):
    make_bad_cache(ferry_paths)  # fresh mtime; only the recovery download should fire
    calls = []

    async def fake_download():
        calls.append(True)
        write_ferry_zip(ferry_paths)

    monkeypatch.setattr(ferry_static, "_download_zip", fake_download)
    data = await ferry_static.load_ferry_static()
    assert calls == [True]  # exactly one re-download
    assert "18" in data["stops"]


async def test_fresh_but_empty_cache_redownloads_and_recovers(ferry_paths, monkeypatch):
    # A fresh cache that parses to ZERO stops is treated as unusable, so the
    # loader re-downloads once instead of trusting the fresh mtime and wedging
    # until MAX_AGE_DAYS (the empty-valid-cache guard 13a's review hardened).
    write_ferry_zip(ferry_paths, stops=[])  # fresh, valid zip, no stops
    calls = []

    async def fake_download():
        calls.append(True)
        write_ferry_zip(ferry_paths)  # the corrected feed

    monkeypatch.setattr(ferry_static, "_download_zip", fake_download)
    data = await ferry_static.load_ferry_static()
    assert calls == [True]
    assert "18" in data["stops"]


# ---------------- redirect-following download (the ferry-specific quirk) ----------------


class _RedirectHandler(http.server.BaseHTTPRequestHandler):
    """Serve a 302 from /gtfs.aspx to /gtfs.zip, and the zip bytes at /gtfs.zip:
    the exact shape the real Connexionz utility URL exhibits, so the test proves
    the loader follows the redirect (httpx would NOT by default)."""

    def do_GET(self):  # noqa: N802 (BaseHTTPRequestHandler API)
        if self.path.endswith("gtfs.aspx"):
            self.send_response(302)
            self.send_header("Location", "/gtfs.zip")
            self.end_headers()
        elif self.path.endswith("gtfs.zip"):
            body = _zip_bytes()
            self.send_response(200)
            self.send_header("Content-Type", "application/zip")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        else:
            self.send_response(404)
            self.end_headers()

    def log_message(self, *args):  # silence the test server
        pass


async def test_download_follows_the_302_to_the_resource_zip(ferry_paths, monkeypatch):
    server = http.server.HTTPServer(("127.0.0.1", 0), _RedirectHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        host, port = server.server_address
        monkeypatch.setattr(ferry_static, "FERRY_STATIC_URL", f"http://{host}:{port}/gtfs.aspx")
        # No cache exists, so the loader must download by following the redirect;
        # a non-following client would raise_for_status on the 302's empty body.
        data = await ferry_static.load_ferry_static()
    finally:
        server.shutdown()
        thread.join(timeout=5)
    assert data["stops"]["18"]["name"] == "Wall St/Pier 11"
    assert data["trips"]["t1"]["route_id"] == "ER"


# ---------------- golden tests over the trimmed real fixture ----------------
#
# fixtures/ferry_gtfs/ is a trimmed copy of the real Connexionz feed written by
# backend/scripts/gen_ferry_fixture.py (trim rule documented there: stops and
# routes in full, trips cut to 3 modal + 1 per variant shape per (route,
# direction), shapes cut to the referenced ids). These tests skip until the
# fixture is generated, which needs egress to nycferry.connexionz.net. In CI a
# missing fixture fails instead; see conftest.golden_fixture_guard.

golden = golden_fixture_guard(FIXTURE_DIR / "stops.txt", "backend/scripts/gen_ferry_fixture.py")

EXPECTED_ROUTE_COLORS = {
    "AS": "FF6B00",
    "ER": "00839C",
    "GI": "9795A0",
    "RES": "00A1E1",
    "RR": "FF8672",
    "RS": "4E008E",
    "RWS": "00A1E1",
    "SB": "FFD100",
    "SG": "D0006F",
}
EXPECTED_ROUTE_NAMES = {
    "AS": "Astoria",
    "ER": "East River",
    "GI": "Governors Island Shuttle",
    "RR": "Rockaway",
    "SB": "South Brooklyn",
    "SG": "St. George",
}


def _fixture(name):
    return io.BytesIO((FIXTURE_DIR / name).read_bytes())


@golden
def test_golden_stop_count_and_wheelchair_passthrough():
    stops = ferry_static._parse_stops(_fixture("stops.txt"))
    # 50 stops, verified live 2026-07-07; stops.txt is committed in full.
    assert len(stops) == 50
    # At least one accessible and one non-affirmative stop, so the passthrough
    # is exercised over real data (the feed carries 1 or blank).
    accessible = [s for s in stops.values() if s["wheelchair"]]
    assert accessible and len(accessible) < len(stops)
    assert all(isinstance(s["wheelchair"], bool) for s in stops.values())


@golden
def test_golden_route_table_colors_and_names():
    routes = ferry_static._parse_routes(_fixture("routes.txt"))
    # Colors compared case-insensitively: the loader stores route_color
    # verbatim, and only the hex value (not its case) is contractual.
    got_colors = {rid: (r["color"] or "").upper() for rid, r in routes.items()}
    assert got_colors == EXPECTED_ROUTE_COLORS
    for rid, name in EXPECTED_ROUTE_NAMES.items():
        assert routes[rid]["long_name"] == name


@golden
def test_golden_every_trip_resolves_to_a_route():
    # THE 14b JOIN, pinned: the realtime feed carries empty route_id, so a
    # train's route is recovered by joining trip_id through trips.txt. Every
    # trip must therefore carry a non-null route_id, and every route must be
    # represented so the join covers all nine.
    trips = ferry_static._parse_trips(_fixture("trips.txt"))
    assert trips
    assert all(t["route_id"] for t in trips.values())
    trip_routes = {tid: t["route_id"] for tid, t in trips.items()}
    assert set(trip_routes.values()) == set(EXPECTED_ROUTE_COLORS)


@golden
def test_golden_every_trip_shape_resolves():
    trips = ferry_static._parse_trips(_fixture("trips.txt"))
    shapes = ferry_static._parse_shapes(_fixture("shapes.txt"))
    referenced = {t["shape_id"] for t in trips.values() if t["shape_id"]}
    assert referenced and referenced <= set(shapes)


@golden
def test_golden_modal_variant_spread_is_exercised():
    # Five routes carry multiple shape variants in some (route, direction), the
    # deepest being East River with 4 (verified live). The trim keeps every
    # variant, so the fixture still carries the spread that makes modal
    # selection matter.
    trips = ferry_static._parse_trips(_fixture("trips.txt"))
    by_group: dict[tuple[str, str | None], set] = defaultdict(set)
    for t in trips.values():
        if t["route_id"] and t["shape_id"]:
            by_group[(t["route_id"], t["direction_id"])].add(t["shape_id"])
    multi_variant_routes = {rid for (rid, _dir), sids in by_group.items() if len(sids) > 1}
    assert len(multi_variant_routes) == 5
    assert max(len(sids) for sids in by_group.values()) == 4
    assert "ER" in multi_variant_routes


@golden
def test_golden_route_shapes_are_the_modal_picks():
    trips = ferry_static._parse_trips(_fixture("trips.txt"))
    shapes = ferry_static._parse_shapes(_fixture("shapes.txt"))
    routes_table = ferry_static._parse_routes(_fixture("routes.txt"))
    built = ferry_static.build_ferry_route_shapes(trips, shapes, routes_table)
    # Every route with drawable geometry appears, and each kept polyline is a
    # modal pick for one of the route's directions (never a minority variant).
    assert built
    modal_by_route: dict[str, list] = defaultdict(list)
    counts: dict[str, dict] = defaultdict(lambda: defaultdict(lambda: defaultdict(int)))
    for t in trips.values():
        if t["route_id"] and t["shape_id"]:
            counts[t["route_id"]][t["direction_id"]][t["shape_id"]] += 1
    for route_id, by_dir in counts.items():
        for tally in by_dir.values():
            modal = min(tally, key=lambda s: (-tally[s], s))
            modal_by_route[route_id].append(shapes[modal])
    for entry in built:
        for polyline in entry["shape"]:
            assert polyline in modal_by_route[entry["id"]]
