"""Tests for the NJ Transit static GTFS loader (backend/njt_static.py).

Two layers, matching test_ferry_static.py's house discipline:

  - Synthetic tables (io.BytesIO and in-memory zips, no disk beyond tmp_path, no
    network) exercise the pure parsers, the validators, the derived indexes, and
    the loader's control flow. Every band and boundary is asserted at its edge.
  - Golden tests read the committed trimmed copy of the REAL feed under
    fixtures/njt_gtfs/ (generated by backend/scripts/gen_njt_fixture.py, trim rule
    documented there) and assert the live-verified facts: 12 routes all carrying
    route_type 113, the two identity stops, the west-of-Hudson stations carrying
    MAIN and BERG rather than a Port Jervis route id, and the trip_short_name
    train numbers 15b joins on. They skip loudly when the fixture has not been
    generated yet; in CI a missing fixture FAILS.

THE FIXTURE NEEDS CREDENTIALS TO GENERATE, which is new for this repo: NJ
Transit's archive is behind an account, so no CI job and no agent can produce it.
The goldens below are therefore dormant-and-loud until someone with a RailData
registration runs the generator and commits the result, which is exactly what
conftest.golden_fixture_guard is for.

THE SERVICE-DATE GUARD IS TESTED WITH AN INJECTED CLOCK, never the wall clock.
That is not merely tidiness: the guard compares against TODAY, so a wall-clock
test would pass or fail depending on the day it ran, and the one case worth
pinning (latest == today exactly, which must PASS) would be unreachable on all
but one day per fixture.
"""

from __future__ import annotations

import io
import re
import zipfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

import njt_auth
import njt_static
import route_geometry
from conftest import golden_fixture_guard
from feeds.shared import NYC_TZ
from static_shared import StaticValidationError

pytestmark = pytest.mark.anyio

# datetime.UTC is 3.11+; spelled this way so the module parses on the documented
# floor without depending on the alias landing in the version that runs it.
UTC = timezone.utc

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "njt_gtfs"
golden = golden_fixture_guard(
    FIXTURE_DIR / "stops.txt",
    "backend/scripts/gen_njt_fixture.py (needs NJT_USERNAME and NJT_PASSWORD)",
)
# A SECOND SENTINEL, for the route-line goldens only (15c). shapes.txt arrives in
# its own refresh after the other six members are already committed, so gating it
# on stops.txt would make every line golden pass vacuously the moment the 15a
# fixture existed. Same rule as the first guard: skip locally, FAIL in CI, and name
# the command that fixes it. test_feeds_path.py carries two guards for the same
# reason.
golden_shapes = golden_fixture_guard(
    FIXTURE_DIR / "shapes.txt",
    "backend/scripts/gen_njt_fixture.py --shapes-only (needs NJT_USERNAME and NJT_PASSWORD)",
)

# A fixed instant with a comfortable margin from any local midnight, so the
# service-date arithmetic below is about the guard rather than about the clock:
# 2026-08-06 12:00 EDT.
NOW = datetime(2026, 8, 6, 12, 0, tzinfo=NYC_TZ).timestamp()


def _ny_date(now: float, offset_days: int) -> str:
    """YYYYMMDD in New York, `offset_days` from `now`. Built by calendar
    arithmetic on the local date rather than by adding seconds, so a DST boundary
    inside the offset cannot silently move the answer by a day."""
    day = datetime.fromtimestamp(now, NYC_TZ).date() + timedelta(days=offset_days)
    return day.strftime("%Y%m%d")


# ---------------------------------------------------------------------------
# Table builders: NJT-shaped rows, per the 2026-08-05 probe
# ---------------------------------------------------------------------------

AGENCY = (
    "agency_id,agency_name,agency_url,agency_timezone\nNJT,NJ TRANSIT,https://x,America/New_York\n"
)

# route_type 113 on every row (the GTFS extended "Rail Service" type), and an
# EMPTY route_text_color, which is what all 12 real routes carry.
ROUTES = (
    "route_id,route_short_name,route_long_name,route_type,route_color,route_text_color\n"
    "1,NEC,Northeast Corridor,113,EF3E42,\n"
    "5,BERG,Bergen County Line,113,C0C0C0,\n"
    "6,MAIN,Main Line,113,FFD700,\n"
    "13,PASC,Pascack Valley,113,A2A4A3,\n"
)

# FLAT stops: no location_type, no parent_station, no wheelchair column anywhere.
STOPS = (
    "stop_id,stop_code,stop_name,stop_lat,stop_lon\n"
    "109,NY,New York Penn Station,40.750568,-73.993519\n"
    "112,NP,Newark Penn Station,40.734924,-74.164581\n"
    "38,HB,Hoboken,40.734984,-74.027683\n"
    "125,PJ,Port Jervis,41.377300,-74.691700\n"
    "160,,No Coords,,\n"  # malformed coordinate: skipped by the parser
)

TRIPS = (
    "route_id,service_id,trip_id,trip_headsign,direction_id,trip_short_name\n"
    "1,SVC1,T1,New York,0,3800\n"
    "6,SVC1,T2,Port Jervis,1,1600\n"
    "13,SVC1,T3,Hoboken,1,1610\n"
    ",SVC1,T4,Orphan,0,9999\n"  # no route_id: contributes nothing to the routes fold
)

STOP_TIMES = (
    "trip_id,arrival_time,departure_time,stop_id,stop_sequence\n"
    "T1,07:00:00,07:00:30,112,1\n"
    "T1,07:20:00,07:20:30,109,2\n"
    "T2,23:40:00,23:41:00,38,1\n"
    "T2,25:10:00,25:11:00,125,2\n"  # past midnight: hours exceed 24, by design
    "T3,08:00:00,08:00:00,38,1\n"
    "T3,08:25:00,08:25:00,112,2\n"
    "T4,09:00:00,09:00:00,109,1\n"
)


def _calendar_dates(now: float = NOW, last_offset: int = 60, first_offset: int = -7) -> str:
    return (
        "service_id,date,exception_type\n"
        f"SVC1,{_ny_date(now, first_offset)},1\n"
        f"SVC1,{_ny_date(now, last_offset)},1\n"
    )


def _members(**overrides: str) -> dict[str, str]:
    """A valid NJT archive's members. NOTE what is absent: no calendar.txt and no
    feed_info.txt, because the real feed ships neither and a fixture that carried
    them would test a loader nobody wrote."""
    members = {
        "agency.txt": AGENCY,
        "routes.txt": ROUTES,
        "stops.txt": STOPS,
        "trips.txt": TRIPS,
        "stop_times.txt": STOP_TIMES,
        "calendar_dates.txt": _calendar_dates(),
        # Present, and since 15c parsed, though the trips above carry no shape_id
        # column: `wanted` is empty for this archive, so the parse reads every row
        # and keeps nothing, which is the case the shapes tests below start from.
        "shapes.txt": "shape_id,shape_pt_sequence,shape_pt_lat,shape_pt_lon\ns1,1,40.7,-74.0\n",
    }
    members.update(overrides)
    return members


def _zip_bytes(members: dict[str, str], drop: tuple[str, ...] = ()) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, body in members.items():
            if name not in drop:
                zf.writestr(name, body)
    return buf.getvalue()


def _open(members: dict[str, str], drop: tuple[str, ...] = ()) -> zipfile.ZipFile:
    return zipfile.ZipFile(io.BytesIO(_zip_bytes(members, drop)))


def _parse(table: str, parser):
    return parser(io.BytesIO(table.encode()))


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------


def test_stops_parse_flat_with_no_wheelchair_field():
    stops = _parse(STOPS, njt_static._parse_stops)
    assert set(stops) == {"109", "112", "38", "125"}  # 160 has no usable coordinate
    assert stops["109"] == {
        "id": "109",
        "name": "New York Penn Station",
        "lat": 40.750568,
        "lon": -73.993519,
    }
    # THE ABSENCE IS THE ASSERTION. FerryStop carries a wheelchair bool because the
    # ferry feed publishes one; NJ Transit publishes no accessibility data at all,
    # and a hardcoded False would read downstream as an affirmative "not
    # accessible" the feed never said.
    assert "wheelchair" not in stops["109"]


def test_routes_carry_the_extended_type_and_a_null_text_color():
    routes = _parse(ROUTES, njt_static._parse_routes)
    assert len(routes) == 4
    # route_type 113 passes through verbatim: it is the GTFS EXTENDED "Rail
    # Service" type, not one of the classic 0-7 basic types, and anything
    # switch-casing 0-7 falls through it.
    assert {r["type"] for r in routes.values()} == {"113"}
    assert routes["13"]["short_name"] == "PASC"
    # Empty on all 12 real routes, so it must arrive as None rather than "" and
    # must not be defaulted to a contrast colour by the parser.
    assert routes["13"]["text_color"] is None


def test_trips_carry_the_train_number_and_the_headsign():
    trips = _parse(TRIPS, njt_static._parse_trips)
    # short_name IS the train number and 15b's second join key (745/745 on the probe).
    assert trips["T1"]["short_name"] == "3800"
    # The ONLY place Port Jervis is named anywhere in this feed: it has no route id.
    assert trips["T2"]["headsign"] == "Port Jervis"
    assert trips["T2"]["route_id"] == "6"  # MAIN, not a Port Jervis route
    assert trips["T4"]["route_id"] is None


def test_stop_times_keep_times_and_survive_hours_past_24():
    calls = _parse(STOP_TIMES, njt_static._parse_stop_times)
    assert [c["stop_id"] for c in calls["T1"]] == ["112", "109"]
    assert calls["T1"][0]["arrival"] == 7 * 3600
    # 25:10:00 is a real GTFS time, not a malformed one: a train departing after
    # midnight belongs to the previous service day and is published past 24h.
    assert calls["T2"][1]["arrival"] == 25 * 3600 + 10 * 60


@pytest.mark.parametrize(
    ("value", "expected"),
    [
        ("00:00:00", 0),
        ("07:05:09", 7 * 3600 + 5 * 60 + 9),
        ("25:10:00", 25 * 3600 + 10 * 60),
        ("", None),
        ("   ", None),
        ("7:05", None),
        ("aa:bb:cc", None),
        ("-1:00:00", None),
    ],
)
def test_gtfs_seconds(value, expected):
    assert njt_static.gtfs_seconds(value) == expected


def test_calendar_dates_counts_only_added_rows():
    """A removal says a service does NOT run that day. Counting one toward the
    service span would let a feed whose real service ended in March pass the
    staleness guard on the strength of a cancellation published for December."""
    table = (
        "service_id,date,exception_type\n"
        "SVC1,20260801,1\n"
        "SVC1,20260802,1\n"
        "SVC1,20991231,2\n"  # a removal far in the future: must NOT extend the span
        "SVC1,2026,1\n"  # malformed date: dropped
        ",20260803,1\n"  # no service_id: dropped
    )
    dates = _parse(table, njt_static._parse_calendar_dates)
    assert dates == {"SVC1": {"20260801", "20260802"}}
    assert njt_static.latest_service_date(dates) == "20260802"


def test_latest_service_date_of_nothing_is_none():
    assert njt_static.latest_service_date({}) is None
    assert njt_static.latest_service_date({"SVC1": set()}) is None


# ---------------------------------------------------------------------------
# Validators
# ---------------------------------------------------------------------------


def test_a_calendar_dates_only_feed_validates():
    """THE HEADLINE ACCEPTANCE CASE. This feed ships no calendar.txt and no
    feed_info.txt; a validator that required either would reject every valid NJ
    Transit publication, forever, with a message about a missing member that is
    never coming."""
    with _open(_members()) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)
        njt_static.validate_njt_publication(zf, now=NOW)


# --- a feed that adopts the ordinary GTFS shape ----------------------------
#
# calendar.txt is not FORBIDDEN, only unrequired, and "not read at all" was the
# wrong answer to what happens if it appears. These three variants are the ones
# that matter, and all three used to produce a CONFIDENT WRONG ANSWER: two
# rejections whose message named the wrong cause, and one acceptance that
# published an end date 15 months early. The span is now the later of calendar's
# end_date and the latest added calendar_dates day, which gets all three right.

_CAL = "service_id,monday,tuesday,start_date,end_date\nSVC1,1,1,{start},{end}\n"


def test_a_removals_only_calendar_dates_is_fine_when_calendar_carries_the_span():
    """Variant (a). With calendar.txt present, calendar_dates is an EXCEPTION list
    again, and a feed whose only exceptions are cancellations is perfectly ordinary.
    Rejecting it as "schedules no service days" named the wrong cause entirely."""
    members = _members(
        **{
            "calendar.txt": _CAL.format(start=_ny_date(NOW, -30), end=_ny_date(NOW, 400)),
            "calendar_dates.txt": f"service_id,date,exception_type\nSVC1,{_ny_date(NOW, 120)},2\n",
        }
    )
    with _open(members) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)
    assert njt_static._service_span(_open(members)) == _ny_date(NOW, 400)


def test_a_conventional_calendar_dates_is_judged_on_calendars_end_date():
    """Variant (b). Exception-style calendar_dates whose few ADDED rows are all in
    the past, over a calendar.txt running another year. The feed schedules service
    for months; judging it on the additive rows alone rejected it as expired."""
    members = _members(
        **{
            "calendar.txt": _CAL.format(start=_ny_date(NOW, -30), end=_ny_date(NOW, 400)),
            "calendar_dates.txt": (
                f"service_id,date,exception_type\nSVC1,{_ny_date(NOW, -20)},1\n"
                f"SVC1,{_ny_date(NOW, 150)},2\n"
            ),
        }
    )
    with _open(members) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)


def test_the_span_is_the_later_of_the_two_calendars():
    """Variant (c), the quiet one. A near-future ADD plus a far-future calendar
    end_date used to be ACCEPTED while publishing the add as the feed's end date, so
    /api/status, the warmup log and the monitor's band all reported a number 15
    months early and the guard would start rejecting a healthy feed on that day."""
    members = _members(
        **{
            "calendar.txt": _CAL.format(start=_ny_date(NOW, -30), end=_ny_date(NOW, 400)),
            "calendar_dates.txt": f"service_id,date,exception_type\nSVC1,{_ny_date(NOW, 30)},1\n",
        }
    )
    assert njt_static._service_span(_open(members)) == _ny_date(NOW, 400)
    # And the other direction: calendar_dates reaching past calendar's end wins.
    members = _members(
        **{
            "calendar.txt": _CAL.format(start=_ny_date(NOW, -30), end=_ny_date(NOW, 10)),
            "calendar_dates.txt": f"service_id,date,exception_type\nSVC1,{_ny_date(NOW, 300)},1\n",
        }
    )
    assert njt_static._service_span(_open(members)) == _ny_date(NOW, 300)


def test_a_calendar_with_no_usable_end_date_contributes_nothing():
    """A calendar.txt whose end_date is blank or impossible must not rescue an
    expired feed, and must not break a healthy one either: it simply adds nothing
    and the calendar_dates answer stands."""
    for end in ("", "20261332", "not-a-date"):
        members = _members(
            **{
                "calendar.txt": _CAL.format(start=_ny_date(NOW, -30), end=end),
                "calendar_dates.txt": _calendar_dates(last_offset=-1, first_offset=-40),
            }
        )
        with _open(members) as zf:
            with pytest.raises(StaticValidationError, match="expired"):
                njt_static.validate_njt_archive(zf, now=NOW)


# --- an eight-digit string is not a date ------------------------------------


@pytest.mark.parametrize(
    "impossible", ["20261301", "20260230", "20260000", "20261232", "99999999", "00000000"]
)
def test_an_impossible_date_cannot_extend_the_service_span(impossible):
    """THE GUARD RETURNS THE HEALTHY ANSWER ON EXACTLY THE INPUT IT CANNOT READ, if
    the parser admits any eight digits. The comparison is lexicographic, so
    "20261301" (month 13) sorts above every real 2026 date: one such row anywhere in
    an 8,697-row table made a fully expired schedule look like one running into next
    year, and the monitor could not cover for it (it downgrades an unparseable date
    to WARN, and a WARN never fails a run).

    So the date is really parsed and an impossible one is dropped, exactly like a
    malformed coordinate is dropped from stops.
    """
    table = f"service_id,date,exception_type\nSVC1,{_ny_date(NOW, -400)},1\nSVC1,{impossible},1\n"
    dates = _parse(table, njt_static._parse_calendar_dates)
    assert njt_static.latest_service_date(dates) == _ny_date(NOW, -400)
    with _open(_members(**{"calendar_dates.txt": table})) as zf:
        with pytest.raises(StaticValidationError, match="expired"):
            njt_static.validate_njt_archive(zf, now=NOW)


# --- rows that are not boardable stops --------------------------------------


def test_non_boardable_rows_never_become_markers():
    """This feed is FLAT today (no location_type, no parent_station), and the parser
    assumes that. What it does NOT assume is that a row it has never seen is a stop:
    a parent station, an entrance, a generic node and a boarding area are all things
    a train does not call at, and placing them puts a station pin and a street-
    entrance pin a few metres from the platform that actually carries the routes,
    each with no routes of its own. Nothing downstream could catch that: the
    monitor's stop count is a lower bound and the identity check passes because a
    parent keeps the station's name.
    """
    table = (
        "stop_id,stop_name,stop_lat,stop_lon,location_type,parent_station\n"
        "109,New York Penn Station,40.750568,-73.993519,1,\n"  # parent station
        "109A,NY Penn Track 1,40.750568,-73.993519,0,109\n"  # boardable platform
        "109E,NY Penn 7th Ave entrance,40.750100,-73.993000,2,109\n"  # entrance
        "109N,NY Penn concourse,40.750200,-73.993100,3,109\n"  # generic node
        "112,Newark Penn Station,40.734924,-74.164581,,\n"  # today's flat shape
    )
    stops = _parse(table, njt_static._parse_stops)
    assert set(stops) == {"109A", "112"}, (
        "only boardable rows (blank or 0 location_type) may become markers"
    )


def test_a_publication_may_omit_shapes_and_still_be_servable():
    """RENAMED IN 15c, because the old name gave the old reason. It used to be
    "shapes may be absent because nothing parses it yet", which was true in 15a and
    is now false: shapes.txt IS parsed. The member stays optional for a different
    and better reason, and one the ferry and PATH loaders do NOT share (both
    require their own shapes.txt): NJ Transit's stations and trains stand without
    geometry, so a publication that dropped 10 MB of lines is still fully servable
    and rejecting it would take the map down to save the decoration."""
    with _open(_members(), drop=("shapes.txt",)) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)


@pytest.mark.parametrize(
    "member",
    ["agency.txt", "routes.txt", "trips.txt", "stops.txt", "stop_times.txt", "calendar_dates.txt"],
)
def test_a_missing_required_member_fails_validation(member):
    with _open(_members(), drop=(member,)) as zf:
        with pytest.raises(StaticValidationError, match=member):
            njt_static.validate_njt_archive(zf, now=NOW)


@pytest.mark.parametrize(
    ("member", "what"),
    [
        ("stops.txt", "stops"),
        ("routes.txt", "routes"),
        ("trips.txt", "trips"),
    ],
)
def test_headers_only_table_fails_the_light_validator(member, what):
    """FINDING 4, FROM BIRTH. A headers-only table is structurally perfect and
    parses cleanly to nothing; promoting one reaches "ready" with an empty map and
    nothing retrying. Three tables are gated on every load, not just stops: a feed
    with stops and no trips places markers that can never carry a train, which is
    the same silent lie one table over.

    stop_times.txt is deliberately NOT in this list; it is the expensive table and
    the publication gate owns it. See the pair of tests below, which pin both halves
    of that split."""
    headers_only = _members()[member].splitlines()[0] + "\n"
    with _open(_members(**{member: headers_only})) as zf:
        with pytest.raises(StaticValidationError, match=f"no usable {what}"):
            njt_static.validate_njt_archive(zf, now=NOW)


def test_a_headers_only_stop_times_passes_the_light_validator():
    """THE FIRST HALF OF THE SPLIT, and it is an ACCEPTANCE test on purpose.

    validate_njt_archive runs on every load of the cached archive, so it pays only
    for the three cheap tables; stop_times.txt is the one table it does not open.
    Asserting that it passes here is what makes the next test's rejection mean
    something: without this, the two validators could be identical again and nobody
    would notice.
    """
    headers_only = STOP_TIMES.splitlines()[0] + "\n"
    with _open(_members(**{"stop_times.txt": headers_only})) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)


def test_a_headers_only_stop_times_fails_the_publication_gate():
    """THE SECOND HALF. A publication may not be promoted over a working archive
    unless the REAL parse of every table the load reads succeeds, and stop_times is
    the table only this gate opens. Delete _parse_open from
    validate_njt_publication and this is what goes red."""
    headers_only = STOP_TIMES.splitlines()[0] + "\n"
    with _open(_members(**{"stop_times.txt": headers_only})) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)  # the light gate still passes
        with pytest.raises(StaticValidationError):
            njt_static.validate_njt_publication(zf, now=NOW)


def test_a_calendar_dates_with_no_added_rows_fails_validation():
    """A headers-only calendar_dates is the finding-4 shape applied to the one
    table this feed cannot degrade around: with no calendar.txt, an empty
    calendar_dates means the publication schedules nothing at all, ever."""
    with _open(_members(**{"calendar_dates.txt": "service_id,date,exception_type\n"})) as zf:
        with pytest.raises(StaticValidationError, match="schedules no service days"):
            njt_static.validate_njt_archive(zf, now=NOW)


def test_a_calendar_dates_of_removals_only_schedules_nothing():
    """Removals do not extend a service span. A table of nothing but cancellations
    (however far in the future they reach) schedules no service, and must be
    rejected rather than read as a feed running until 2099."""
    removals = "service_id,date,exception_type\nSVC1,20991231,2\nSVC1,20991230,2\n"
    with _open(_members(**{"calendar_dates.txt": removals})) as zf:
        with pytest.raises(StaticValidationError, match="schedules no service days"):
            njt_static.validate_njt_archive(zf, now=NOW)


# --- the service-date guard, at its boundary --------------------------------


def test_service_ending_today_is_still_servable():
    """THE BOUNDARY, and the one that has to be inclusive. A feed whose last
    service day is TODAY is running trains right now; rejecting it would drop a
    working system on its final morning, which is strictly worse than serving it
    and letting the monitor's WARN band (which fired 30 days ago) do its job."""
    with _open(_members(**{"calendar_dates.txt": _calendar_dates(last_offset=0)})) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)


def test_service_that_ended_yesterday_is_rejected():
    """THE HARD LINE. With no feed_info.txt there is no feed_end_date to read, so
    calendar_dates IS the expiry signal. A publication that schedules nothing for
    today or any day after cannot be served from, and accepting it would replace a
    working archive with a dead calendar."""
    expired = _calendar_dates(last_offset=-1, first_offset=-40)
    with _open(_members(**{"calendar_dates.txt": expired})) as zf:
        with pytest.raises(StaticValidationError, match="expired"):
            njt_static.validate_njt_archive(zf, now=NOW)


def test_the_guard_reads_today_in_new_york_not_in_utc():
    """A GTFS service date is a local calendar day at the agency. For five hours
    every evening (four under EDT) the UTC date is already tomorrow, so a guard
    reading UTC would declare a feed whose last service day is today EXPIRED at
    20:00 local, on the last evening it is actually serving trains.

    23:30 EDT on 2026-08-06 is 03:30 UTC on 2026-08-07. A feed ending 2026-08-06
    must still validate.
    """
    late_evening = datetime(2026, 8, 6, 23, 30, tzinfo=NYC_TZ).timestamp()
    assert datetime.fromtimestamp(late_evening, UTC).strftime("%Y%m%d") == "20260807"
    table = "service_id,date,exception_type\nSVC1,20260806,1\n"
    with _open(_members(**{"calendar_dates.txt": table})) as zf:
        njt_static.validate_njt_archive(zf, now=late_evening)


def test_the_publication_validator_runs_the_real_parse():
    """Strictly stronger than the archive validator, and the difference is the whole
    point: a publication with clean stops, routes and trips but an undecodable byte
    in stop_times.txt (which the light validator never opens) would otherwise be
    promoted over the last-known-good and then discarded by the loader's residual
    arm, losing both archives.

    KEYED ON stop_times.txt, not on a table both validators read. An earlier version
    of this test corrupted trips.txt, which the LIGHT validator already parses, so
    it passed identically whether or not validate_njt_publication did anything at
    all: deleting the publication gate's extra parse could not fail it. The two
    validators were in fact equivalent at the time, and this test could not see it.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for name, body in _members().items():
            if name == "stop_times.txt":
                # Bytes that are not valid UTF-8, so the table is present and
                # structurally fine but cannot be read.
                zf.writestr(name, STOP_TIMES.encode()[:-5] + b"\xff\xfe\n")
            else:
                zf.writestr(name, body)
    with zipfile.ZipFile(io.BytesIO(buf.getvalue())) as zf:
        # The light gate passes: it does not open stop_times at all.
        njt_static.validate_njt_archive(zf, now=NOW)
        with pytest.raises(StaticValidationError):
            njt_static.validate_njt_publication(zf, now=NOW)


# ---------------------------------------------------------------------------
# Derived indexes
# ---------------------------------------------------------------------------


def _tables():
    return (
        _parse(TRIPS, njt_static._parse_trips),
        _parse(STOP_TIMES, njt_static._parse_stop_times),
    )


def test_stop_routes_folds_through_trips():
    trips, stop_times = _tables()
    index = njt_static.derive_njt_stop_routes(trips, stop_times)
    assert index["112"] == ["1", "13"]  # NEC and Pascack Valley both call there
    assert index["109"] == ["1"]  # T4 has no route_id, so it contributes nothing
    # PORT JERVIS COMES BACK AS MAIN, and that is the feed's own answer rather than
    # a bug: Port Jervis has no route id, so its stations can only report the route
    # their trips run under. Inventing one here would be a fiction.
    assert index["125"] == ["6"]


def test_the_trip_index_is_the_15b_join_target():
    trips, _ = _tables()
    index = njt_static.build_njt_trip_index(trips)
    assert index["T1"] == {"route_id": "1", "headsign": "New York", "short_name": "3800"}
    # A narrowed projection: direction_id and service_id stay in the full parsed
    # table, so what this publishes is exactly what a realtime entity needs.
    assert set(index["T1"]) == {"route_id", "headsign", "short_name"}


def test_the_stop_schedule_is_sorted_and_carries_the_train_number():
    trips, stop_times = _tables()
    schedule = njt_static.build_njt_stop_schedule(trips, stop_times)
    at_112 = schedule["112"]
    assert [call["trip_id"] for call in at_112] == ["T1", "T3"]  # 07:00 before 08:25
    assert at_112[0]["train"] == "3800"
    assert at_112[0]["route_id"] == "1"
    at_125 = schedule["125"]
    assert at_125[0]["arrival"] == 25 * 3600 + 10 * 60  # past-midnight time preserved


def test_a_call_with_no_times_sorts_last_rather_than_first():
    """float("inf"), not 0. A timeless call sorted to 0 would sit ahead of every
    real departure, which is the wrong end of the list to be wrong at."""
    stop_times = _parse(
        "trip_id,arrival_time,departure_time,stop_id,stop_sequence\n"
        "T1,,,109,1\n"
        "T1,07:00:00,07:00:00,112,2\n"
        "T3,06:00:00,06:00:00,109,1\n",
        njt_static._parse_stop_times,
    )
    trips, _ = _tables()
    schedule = njt_static.build_njt_stop_schedule(trips, stop_times)
    assert [call["trip_id"] for call in schedule["109"]] == ["T3", "T1"]


def test_the_stop_schedule_falls_back_to_departure_when_arrival_is_blank():
    stop_times = _parse(
        "trip_id,arrival_time,departure_time,stop_id,stop_sequence\n"
        "T1,,06:00:00,109,1\n"
        "T3,07:00:00,,109,1\n",
        njt_static._parse_stop_times,
    )
    trips, _ = _tables()
    schedule = njt_static.build_njt_stop_schedule(trips, stop_times)
    assert [call["trip_id"] for call in schedule["109"]] == ["T1", "T3"]


# ---------------------------------------------------------------------------
# The loader
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def _fresh_token_cache(monkeypatch):
    """A clean token cache per test. The production cache is process-wide on
    purpose (the static loader and, from 15b, the pollers must share one token),
    which makes it exactly the kind of state that leaks between tests."""
    monkeypatch.setattr(njt_auth, "TOKEN_CACHE", njt_auth.TokenCache())


def _fake_transport(zip_bytes: bytes, calls: list | None = None):
    async def transport(url, form, timeout_s):
        if calls is not None:
            calls.append((url, dict(form)))
        if url.endswith("getToken"):
            return 200, b'{"UserToken":"t1"}'
        return 200, zip_bytes

    return transport


async def test_absent_credentials_raise_before_any_disk_or_network(monkeypatch, tmp_path):
    """NOT-CONFIGURED IS A DISTINCT STATE, and it is reached before anything else
    happens: no cache read, no mint, no fetch. Collapsing it into the ordinary
    empty-dict failure would put an unconfigured deployment into a retry loop that
    can never succeed against an endpoint that would reject it anyway.

    The archive path is pointed at a file that DOES exist and is valid, so a loader
    that consulted the cache first would return data and fail this test. Serving a
    stale archive from a previous credentialed run would make /api/njt-stops answer
    while the status honestly said "not configured", which is the exact composite
    lie this codebase keeps removing.
    """
    cached = tmp_path / "gtfs_njt.zip"
    cached.write_bytes(_zip_bytes(_members()))
    monkeypatch.setattr(njt_static, "NJT_STATIC_ZIP", cached)
    monkeypatch.delenv(njt_auth.USERNAME_VAR, raising=False)
    monkeypatch.delenv(njt_auth.PASSWORD_VAR, raising=False)
    monkeypatch.setattr(njt_auth, "_httpx_post", _explodes())

    with pytest.raises(njt_auth.NjtNotConfigured):
        await njt_static.load_njt_static(now=NOW)


def _explodes():
    async def transport(url, form, timeout_s):
        raise AssertionError(f"no network is allowed here, but {url!r} was requested")

    return transport


async def test_a_good_download_parses_and_promotes(monkeypatch, tmp_path):
    monkeypatch.setenv(njt_auth.USERNAME_VAR, "rider")
    monkeypatch.setenv(njt_auth.PASSWORD_VAR, "secret")
    monkeypatch.setattr(njt_static, "NJT_STATIC_ZIP", tmp_path / "gtfs_njt.zip")
    calls: list = []
    monkeypatch.setattr(njt_auth, "_httpx_post", _fake_transport(_zip_bytes(_members()), calls))

    data = await njt_static.load_njt_static(now=NOW)

    assert set(data["stops"]) == {"109", "112", "38", "125"}
    assert len(data["routes"]) == 4
    assert njt_static.latest_service_date(data["calendar_dates"]) == _ny_date(NOW, 60)
    assert (tmp_path / "gtfs_njt.zip").exists(), "a validated publication must be promoted"
    # THE TOKEN WENT THROUGH THE DOOR. One mint, then the archive request carrying
    # the token as a FORM FIELD, which is the only shape RailData answers.
    assert [url.rsplit("/", 1)[-1] for url, _form in calls] == ["getToken", "getGTFS"]
    assert calls[1][1]["token"] == "t1"


async def test_a_bad_publication_is_rejected_and_nothing_is_promoted(monkeypatch, tmp_path):
    monkeypatch.setenv(njt_auth.USERNAME_VAR, "rider")
    monkeypatch.setenv(njt_auth.PASSWORD_VAR, "secret")
    zip_path = tmp_path / "gtfs_njt.zip"
    monkeypatch.setattr(njt_static, "NJT_STATIC_ZIP", zip_path)
    headers_only = STOPS.splitlines()[0] + "\n"
    bad = _zip_bytes(_members(**{"stops.txt": headers_only}))
    monkeypatch.setattr(njt_auth, "_httpx_post", _fake_transport(bad))

    assert await njt_static.load_njt_static(now=NOW) == {}
    assert not zip_path.exists(), "a rejected publication must never reach the cache path"


async def test_a_failed_download_keeps_serving_the_cached_archive(monkeypatch, tmp_path):
    """Serving old while new is bad, INCLUDING past MAX_AGE_DAYS: the age policy
    exists to pick up upstream's corrections, so it yields to validity rather than
    dropping a working system. The cached archive already passed the service-date
    guard, so this can never serve an expired schedule."""
    monkeypatch.setenv(njt_auth.USERNAME_VAR, "rider")
    monkeypatch.setenv(njt_auth.PASSWORD_VAR, "secret")
    zip_path = tmp_path / "gtfs_njt.zip"
    good = _zip_bytes(_members())
    zip_path.write_bytes(good)
    import os

    old = NOW - njt_static.MAX_AGE_DAYS * 86400 * 2
    os.utime(zip_path, (old, old))
    monkeypatch.setattr(njt_static, "NJT_STATIC_ZIP", zip_path)

    async def failing(url, form, timeout_s):
        if url.endswith("getToken"):
            return 200, b'{"UserToken":"t1"}'
        return 503, b"upstream down"

    monkeypatch.setattr(njt_auth, "_httpx_post", failing)

    data = await njt_static.load_njt_static(now=NOW)
    assert set(data["stops"]) == {"109", "112", "38", "125"}
    assert zip_path.read_bytes() == good, "the cached archive must be byte-untouched"


async def test_an_expired_cached_archive_is_treated_as_absent(monkeypatch, tmp_path):
    """The service-date guard runs on the CACHE too, not only on a publication. A
    cached archive whose schedule expired overnight is rejected here and
    re-downloaded, rather than being served for another MAX_AGE_DAYS because its
    mtime is fresh."""
    monkeypatch.setenv(njt_auth.USERNAME_VAR, "rider")
    monkeypatch.setenv(njt_auth.PASSWORD_VAR, "secret")
    zip_path = tmp_path / "gtfs_njt.zip"
    expired = _calendar_dates(last_offset=-1, first_offset=-40)
    zip_path.write_bytes(_zip_bytes(_members(**{"calendar_dates.txt": expired})))
    monkeypatch.setattr(njt_static, "NJT_STATIC_ZIP", zip_path)
    monkeypatch.setattr(njt_auth, "_httpx_post", _fake_transport(_zip_bytes(_members())))

    data = await njt_static.load_njt_static(now=NOW)
    # The fresh (valid) publication replaced it, which only happens if the expired
    # cache was treated as absent rather than as fresh-by-mtime.
    assert njt_static.latest_service_date(data["calendar_dates"]) == _ny_date(NOW, 60)


# ---------------------------------------------------------------------------
# Shapes and route lines (15c)
# ---------------------------------------------------------------------------
#
# THE SYNTHETIC RAILWAY BELOW IS SHAPED LIKE THE REAL PROBLEM. NJ Transit's North
# Jersey Coast Line splits for Long Branch and Bay Head, and Montclair-Boonton
# splits for Montclair State and Hackettstown, so a dedup that collapses branch
# variants draws a line that stops short of a real terminus, which a rider reads
# as "service ends here". The same feed also publishes a reverse-direction shape
# and short-turn workings for the same route, which must NOT each become their own
# polyline. One trunk, two branches, one reversal and one short-turn is the
# smallest thing that can tell those two apart.

# Lengths are deliberately distinct where the order matters: route_polylines sorts
# variants longest first, and among EQUAL lengths the pre-sort by shape_id decides.
# The trunk is longest, so it seeds `covered` and every other variant is measured
# against a line that already exists.
_TRUNK = [(40.700 + 0.010 * i, -74.100 + 0.010 * i) for i in range(14)]
# Shares the trunk's first 8 points, then leaves it. 4 of its 12 points are new
# (0.33), comfortably over the 0.05 threshold.
_BRANCH_A = _TRUNK[:8] + [(40.780 + 0.010 * i, -74.020 - 0.010 * i) for i in range(4)]
# The other branch off the same 8 shared points, diverging the other way.
_BRANCH_B = _TRUNK[:8] + [(40.760 - 0.010 * i, -73.980 + 0.010 * i) for i in range(4)]
# The same points as the trunk in the opposite order: 0 new, and the point-set
# test is what makes that true without anyone detecting reversal.
_REVERSE = list(reversed(_TRUNK))
# A short-turn working over the middle of the trunk: every point already covered.
_SHORT_TURN = _TRUNK[3:9]


def _shapes_table(shapes: dict[str, list[tuple[float, float]]]) -> str:
    """shapes.txt text for {shape_id: [(lat, lon), ...]}, sequence-numbered from 1."""
    lines = ["shape_id,shape_pt_sequence,shape_pt_lat,shape_pt_lon"]
    for shape_id, points in shapes.items():
        for seq, (lat, lon) in enumerate(points, start=1):
            lines.append(f"{shape_id},{seq},{lat},{lon}")
    return "\n".join(lines) + "\n"


# route 1 gets the whole trunk/branch/reverse/short-turn family; route 6 gets one
# plain line; route 13 references a shape the table does not carry (a dangling
# reference, which a publication is entitled to produce); route 99 exists in
# routes.txt with no trips at all, which is the Meadowlands case.
_GEOM_TRIPS = (
    "route_id,service_id,trip_id,trip_headsign,direction_id,trip_short_name,shape_id\n"
    "1,SVC1,T1,Bay Head,0,3800,s1\n"
    "1,SVC1,T2,Long Branch,0,3802,s2\n"
    "1,SVC1,T3,Bay Head,0,3804,s3\n"
    "1,SVC1,T4,New York,1,3806,s9\n"
    "1,SVC1,T5,Matawan,0,3808,s4\n"
    "6,SVC1,T6,Port Jervis,1,1600,s5\n"
    "13,SVC1,T7,Hoboken,1,1610,s404\n"
)
_GEOM_SHAPES = _shapes_table(
    {
        "s1": _TRUNK,
        "s2": _BRANCH_A,
        "s3": _BRANCH_B,
        "s4": _SHORT_TURN,
        "s5": [(40.90, -74.20), (40.95, -74.30), (41.00, -74.40)],
        "s9": _REVERSE,
        # Referenced by no trip at all: the bound is what must drop it.
        "s7": [(0.0, 0.0), (1.0, 1.0), (2.0, 2.0)],
    }
)
_GEOM_ROUTES = (
    "route_id,route_short_name,route_long_name,route_type,route_color,route_text_color\n"
    "1,NJCL,North Jersey Coast Line,113,03A3DF,\n"
    "6,MAIN,Main Line,113,FFD411,\n"
    "13,PASC,Pascack Valley Line,113,94219A,\n"
    "99,MRL,Meadowlands Rail Line,113,C1AA72,\n"
)


def _geom_members(**overrides: str) -> dict[str, str]:
    return _members(
        **{
            "trips.txt": _GEOM_TRIPS,
            "shapes.txt": _GEOM_SHAPES,
            "routes.txt": _GEOM_ROUTES,
            **overrides,
        }
    )


def _geom_parsed(**overrides: str) -> dict:
    with _open(_geom_members(**overrides)) as zf:
        return njt_static._parse_open(zf)


def test_trips_carry_shape_id_because_nothing_else_links_a_route_to_geometry():
    trips = _parse(_GEOM_TRIPS, njt_static._parse_trips)
    assert trips["T1"]["shape_id"] == "s1"
    # Blank stays None rather than "", so route_geometry's truthiness test reads
    # "this trip contributes no shape" without a second spelling of empty.
    blank = _parse(
        "route_id,service_id,trip_id,trip_headsign,direction_id,trip_short_name,shape_id\n"
        "1,SVC1,T1,New York,0,3800,\n",
        njt_static._parse_trips,
    )
    assert blank["T1"]["shape_id"] is None


def test_only_shape_ids_some_trip_references_are_parsed():
    """THE BOUND, and it is the reason parsing this member is affordable at all:
    shapes.txt is 10 MB of the 11.1 MB payload upstream. s7 is in the table and in
    nobody's trips, so it must not survive; s404 is referenced by a trip and absent
    from the table, which is a publication's right and must not raise."""
    parsed = _geom_parsed()
    assert set(parsed["shapes"]) == {"s1", "s2", "s3", "s4", "s5", "s9"}
    assert "s7" not in parsed["shapes"], "an unreferenced shape must be dropped at the row"
    assert "s404" not in parsed["shapes"], "a dangling reference is absent, never a KeyError"


def test_a_shape_with_no_referencing_trip_costs_nothing_even_when_it_is_enormous():
    """The bound is measured, not asserted: an unreferenced shape with 10,000 points
    leaves the parse output byte-identical, which is what "skipped at the row" means."""
    huge = _shapes_table({"s8": [(40.0 + i / 10000, -74.0) for i in range(10000)]})
    with_huge = _GEOM_SHAPES + huge.split("\n", 1)[1]
    assert _geom_parsed(**{"shapes.txt": with_huge})["shapes"] == _geom_parsed()["shapes"]


def test_shape_points_are_ordered_by_sequence_not_by_file_order():
    scrambled = (
        "shape_id,shape_pt_sequence,shape_pt_lat,shape_pt_lon\n"
        "s1,3,40.3,-74.3\n"
        "s1,1,40.1,-74.1\n"
        "s1,2,40.2,-74.2\n"
    )
    shapes = njt_static._parse_shapes(io.BytesIO(scrambled.encode()), {"s1"})
    assert shapes["s1"] == [[40.1, -74.1], [40.2, -74.2], [40.3, -74.3]]


def test_a_malformed_shape_row_is_skipped_without_costing_its_shape():
    """One bad row must not cost the publication its lines: this member is optional,
    so the whole-file failure it could cause would be a worse answer than a shape
    one point shorter."""
    table = (
        "shape_id,shape_pt_sequence,shape_pt_lat,shape_pt_lon\n"
        "s1,1,40.1,-74.1\n"
        "s1,2,NOT-A-NUMBER,-74.2\n"
        "s1,3,40.3,-74.3\n"
        ",4,40.4,-74.4\n"
    )
    shapes = njt_static._parse_shapes(io.BytesIO(table.encode()), {"s1", ""})
    assert shapes == {"s1": [[40.1, -74.1], [40.3, -74.3]]}


def test_coordinates_are_rounded_to_five_decimals_like_every_other_system():
    table = (
        "shape_id,shape_pt_sequence,shape_pt_lat,shape_pt_lon\ns1,1,40.7505681234,-73.9935194321\n"
    )
    shapes = njt_static._parse_shapes(io.BytesIO(table.encode()), {"s1"})
    assert shapes["s1"] == [[40.75057, -73.99352]]


def test_both_branches_of_a_two_branch_route_survive_the_dedup():
    """THE CLAIM THE WHOLE ARM EXISTS FOR. A line that stops short of a real
    terminus reads to a rider as service ending there, so the branch case is
    asserted by IDENTITY (the branch's own far end is present), not by a count that
    a collapsed pair could still satisfy."""
    parsed = _geom_parsed()
    built = njt_static.build_njt_route_shapes(parsed["trips"], parsed["shapes"], parsed["routes"])
    line = next(entry for entry in built if entry["route"] == "1")
    assert len(line["polylines"]) == 3, "trunk plus both branches, and nothing else"
    drawn = {tuple(point) for polyline in line["polylines"] for point in polyline}
    for name, branch in (("A", _BRANCH_A), ("B", _BRANCH_B)):
        far_end = [round(branch[-1][0], 5), round(branch[-1][1], 5)]
        assert tuple(far_end) in drawn, f"branch {name} lost its terminus"


def test_the_reverse_direction_variant_and_the_short_turn_both_collapse():
    """THE CONTROL for the test above: keeping every variant would also keep both
    branches, so the branch claim only means something beside this one."""
    parsed = _geom_parsed()
    built = njt_static.build_njt_route_shapes(parsed["trips"], parsed["shapes"], parsed["routes"])
    line = next(entry for entry in built if entry["route"] == "1")
    assert len(line["polylines"]) == 3
    # ASSERTED ON ENDPOINTS, not on the point list, because the builder simplifies
    # before it dedups and this synthetic trunk is straight, so its drawn form is
    # its two ends. The claim is unchanged: the trunk is drawn once, not once
    # forwards and once backwards.
    trunk_ends = {
        (round(_TRUNK[0][0], 5), round(_TRUNK[0][1], 5)),
        (round(_TRUNK[-1][0], 5), round(_TRUNK[-1][1], 5)),
    }
    drawn_as_trunk = [p for p in line["polylines"] if {tuple(p[0]), tuple(p[-1])} == trunk_ends]
    assert len(drawn_as_trunk) == 1


def test_the_builder_simplifies_the_geometry_it_draws():
    """THE OTHER HALF OF DEFECT B, and nothing tested it: the fixture arm's
    simplification was pinned but the LOADER's was not, so deleting it from
    build_njt_route_shapes passed the whole suite. That is the half that decides
    what /api/njt-routes ships on every page load, and in production it reads RAW
    geometry (a point every 10 m, 6.9 MB for 29 shapes), not the already-reduced
    fixture. A test over committed geometry cannot see it, because simplifying an
    already-simplified shape is a no-op; this one feeds the builder dense points.
    """
    dense = _shapes_table(
        {"s1": [(40.700 + 0.00002 * i, -74.000 - 0.00002 * i) for i in range(600)]}
    )
    trips = (
        "route_id,service_id,trip_id,trip_headsign,direction_id,trip_short_name,shape_id\n"
        "1,SVC1,T1,New York,0,3800,s1\n"
    )
    parsed = _geom_parsed(**{"shapes.txt": dense, "trips.txt": trips})
    assert len(parsed["shapes"]["s1"]) == 600, "the parse itself must not reduce anything"

    built = njt_static.build_njt_route_shapes(parsed["trips"], parsed["shapes"], parsed["routes"])
    drawn = built[0]["polylines"][0]
    assert len(drawn) < 600, "the builder served every published point"
    # EXACTLY what simplification would give, not merely fewer points: a builder that
    # sampled or truncated would also be "fewer".
    assert drawn == route_geometry.simplify_polyline(
        parsed["shapes"]["s1"], route_geometry.NJT_SIMPLIFY_EPS
    )


def test_a_route_with_no_trips_is_absent_from_the_build_rather_than_empty():
    """The Meadowlands case in miniature: route 99 is in routes.txt, no trip
    references it, so it has no line to draw and no name to carry."""
    parsed = _geom_parsed()
    built = njt_static.build_njt_route_shapes(parsed["trips"], parsed["shapes"], parsed["routes"])
    assert "99" not in {entry["route"] for entry in built}
    # And a route whose only shape reference dangles goes the same way.
    assert "13" not in {entry["route"] for entry in built}


def test_the_build_carries_the_feeds_own_colours_and_invents_no_text_colour():
    parsed = _geom_parsed()
    built = njt_static.build_njt_route_shapes(parsed["trips"], parsed["shapes"], parsed["routes"])
    line = next(entry for entry in built if entry["route"] == "1")
    assert line["name"] == "North Jersey Coast Line"
    assert line["color"] == "03A3DF"
    # NULL, not a computed contrast colour: this feed publishes route_text_color
    # empty on every route, and inventing one here would hide that it said nothing.
    assert line["text_color"] is None


def test_the_build_is_sorted_and_stable_across_calls():
    parsed = _geom_parsed()
    first = njt_static.build_njt_route_shapes(parsed["trips"], parsed["shapes"], parsed["routes"])
    again = njt_static.build_njt_route_shapes(parsed["trips"], parsed["shapes"], parsed["routes"])
    assert [entry["route"] for entry in first] == sorted(entry["route"] for entry in first)
    assert first == again


def test_a_publication_with_no_shapes_txt_still_parses_and_draws_nothing():
    """LINES ARE ADDITIVE. shapes.txt stays out of _REQUIRED_MEMBERS, so a
    publication that drops it validates, parses, keeps every station and trip, and
    yields an empty routes list rather than a failed load."""
    members = _geom_members()
    with _open(members, drop=("shapes.txt",)) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)  # must not raise
        parsed = njt_static._parse_open(zf)
    assert parsed["shapes"] == {}
    assert parsed["stops"] and parsed["trips"], "stations and trains are untouched"
    assert (
        njt_static.build_njt_route_shapes(parsed["trips"], parsed["shapes"], parsed["routes"]) == []
    )


def test_an_unreadable_shapes_txt_costs_the_lines_and_nothing_else():
    """THE GUARD SEEN TO FIRE for the additive promise. Undecodable bytes in a
    REQUIRED member correctly fail the publication; in this one they must not,
    because a corrupt 10 MB of geometry taking down the stations and the trains is
    exactly the trade keeping shapes.txt out of _REQUIRED_MEMBERS refuses.

    The control is the second half: the same bytes in stops.txt DO raise, so this
    test cannot pass by the parse being tolerant everywhere."""
    # RAW BYTES, not a str with high code points: writestr would re-encode those as
    # valid UTF-8 and the test would pass while decoding fine, which is the shape of
    # a test that proves nothing.
    undecodable = b"shape_id,shape_pt_sequence,shape_pt_lat,shape_pt_lon\n\xff\xfe\xff\n"
    members = dict(_geom_members())
    members["shapes.txt"] = undecodable
    with _open(members) as zf:
        parsed = njt_static._parse_open(zf)
    assert parsed["shapes"] == {}
    assert parsed["stops"] and parsed["trips"] and parsed["routes"]

    broken_required = dict(_geom_members())
    broken_required["stops.txt"] = b"stop_id,stop_name,stop_lat,stop_lon\n\xff\xfe\xff\n"
    with _open(broken_required) as zf:
        with pytest.raises(UnicodeDecodeError):
            njt_static._parse_open(zf)


def test_shapes_txt_is_not_a_required_member():
    """Stated as its own assertion because the whole additive-degradation claim
    rests on it, and a future edit to _REQUIRED_MEMBERS would otherwise only show
    up as a mysterious failure three tests away."""
    assert "shapes.txt" not in njt_static._REQUIRED_MEMBERS


def test_the_dedup_threshold_is_a_strict_inequality():
    """A variant adding EXACTLY nothing new must never be kept. Pinned directly at
    route_geometry because the boundary is one character (> versus >=) and a
    mutation there is invisible in any test that only counts branches."""
    trunk = [[0.0, 0.0], [1.0, 1.0], [2.0, 2.0]]
    assert route_geometry.keep_added_geometry([trunk, list(reversed(trunk))]) == [trunk]
    # AT the threshold, refused. Both variants are 20 points, so the length sort is
    # a no-op and the seed is kept first; the second shares 19 of its 20 points, so
    # it adds exactly 1/20 = 0.05, which is not MORE than 0.05.
    seed = [[float(i), 0.0] for i in range(20)]
    at_threshold = seed[:19] + [[99.0, 99.0]]
    assert route_geometry.keep_added_geometry([seed, at_threshold]) == [seed]
    # One point over it, kept: 2/20 = 0.10. The pair is what shows the line sits
    # where the constant says rather than somewhere either case alone would allow.
    over_threshold = seed[:18] + [[99.0, 99.0], [98.0, 98.0]]
    assert route_geometry.keep_added_geometry([seed, over_threshold]) == [seed, over_threshold]


# ---------------------------------------------------------------------------
# Goldens, against the committed trim of the real feed
# ---------------------------------------------------------------------------


def _fixture_zip() -> zipfile.ZipFile:
    members = {
        path.name: path.read_text(encoding="utf-8")
        for path in sorted(FIXTURE_DIR.iterdir())
        if path.suffix == ".txt"
    }
    return _open(members)


@golden
def test_golden_the_fixture_carries_all_twelve_routes_at_type_113():
    with _fixture_zip() as zf:
        routes = njt_static._parse_open(zf)["routes"]
    assert len(routes) == 12, f"the probe found 12 NJT rail routes, fixture has {len(routes)}"
    assert {r["type"] for r in routes.values()} == {"113"}, (
        "all 12 routes carry the GTFS EXTENDED type 113; anything switch-casing 0-7 "
        "falls through it"
    )
    assert all(r["text_color"] is None for r in routes.values()), (
        "route_text_color is empty on all 12, so a renderer needs its own contrast fallback"
    )
    assert routes["13"]["short_name"] == "PASC", "Pascack Valley is a first-class route"


@golden
def test_golden_the_identity_stops_are_flat_and_named():
    with _fixture_zip() as zf:
        stops = njt_static._parse_open(zf)["stops"]
    assert "New York" in stops["109"]["name"]
    assert "Newark" in stops["112"]["name"]
    # FLAT: the parser produces exactly these four keys, and no wheelchair field,
    # because this feed carries no parent stations and no accessibility data.
    assert set(stops["109"]) == {"id", "name", "lat", "lon"}


# THE NINE WEST-OF-HUDSON STATIONS, BY NAME. Not a count, which is the point:
# the fixture is generated by a script that derives this set, so a count-based
# assertion would be checking the generator against itself. These names came from
# the 2026-08-05 probe and are the mandate the trim exists to satisfy.
WEST_OF_HUDSON_STATIONS = (
    "Suffern",  # the junction, and the one exclusivity alone always misses
    "Sloatsburg",
    "Tuxedo",
    "Harriman Station",
    "Salisbury Mills",
    "Campbell Hall",
    "Middletown, NY",
    "Otisville",
    "Port Jervis",
)


@golden
def test_golden_every_west_of_hudson_station_is_in_the_fixture_by_name():
    """THE MANDATE, ASSERTED WHERE NO GENERATOR CAN SATISFY IT BY ACCIDENT.

    The trim is supposed to carry the whole Port Jervis line, and it has now had
    two different bugs that silently dropped stations: a headsign-keyed trip set
    that cancelled itself to empty, and a lexicographic pick of two trips that
    could land on short-turns. Both were invisible because every check on them was
    derived from the same broken computation.

    This is the belt under those suspenders. It reads the committed fixture and
    demands nine specific station NAMES, so a future fixture that violates the
    mandate fails in CI no matter how it was produced, no matter which heuristic
    generated it, and no matter whether that heuristic thought it had succeeded.

    Names rather than stop ids because a rename is a fact worth failing on: this
    feed's ids are small integers that collide across systems, and 15a's identity
    checks are by name for the same reason.
    """
    with _fixture_zip() as zf:
        stops = njt_static._parse_open(zf)["stops"]
    present = {stop["name"] for stop in stops.values()}
    missing = [name for name in WEST_OF_HUDSON_STATIONS if name not in present]
    assert not missing, (
        f"the fixture is missing west-of-Hudson stations {missing}. The trim must keep a "
        "Port Jervis trip that serves the whole line; see njt_fixture_trim's coverage "
        "selection, which chooses trips by what they cover rather than by trip id order."
    )


@golden
def test_golden_the_west_of_hudson_stations_are_actually_served_by_a_kept_trip():
    """Present in stops.txt is not enough: the station has to be REACHABLE in the
    fixture, or the arrivals and placement goldens have a marker with no service.

    Distinct from the test above because the two fail for different reasons. A
    station can reach stops.txt on the coat-tails of some other line's trip through
    the mandated-stop top-up, which is the fallback for a genuinely unserved
    station and is deliberately allowed; what must not happen quietly is the WHOLE
    line arriving that way, with no Port Jervis trip in the fixture at all.
    """
    with _fixture_zip() as zf:
        data = njt_static._parse_open(zf)
    by_name = {stop["name"]: stop_id for stop_id, stop in data["stops"].items()}
    pj_trips = {
        trip_id
        for trip_id, trip in data["trips"].items()
        if "port jervis" in (trip["headsign"] or "").lower()
    }
    assert pj_trips, "a trip must NAME the line, or its identity is unrecoverable"
    served = {
        call["stop_id"] for trip_id in pj_trips for call in data["stop_times"].get(trip_id, [])
    }
    unserved = [
        name
        for name in WEST_OF_HUDSON_STATIONS
        if by_name.get(name) and by_name[name] not in served
    ]
    assert not unserved, (
        f"west-of-Hudson stations {unserved} are in stops.txt but no Port-Jervis-headsigned "
        "trip in the fixture calls at them, so nothing in the fixture connects them to the line"
    )


@golden
def test_golden_west_of_hudson_stations_carry_main_and_bergen_route_ids():
    """PORT JERVIS HAS NO ROUTE OF ITS OWN, and this is the assertion that keeps a
    later phase from quietly "fixing" that into a fiction. Its stations report the
    MAIN (6) and BERG (5) ids their trips run under, because those are the only
    route ids the feed gives them; the Port Jervis identity lives in trip_headsign
    and nowhere else."""
    with _fixture_zip() as zf:
        data = njt_static._parse_open(zf)
    index = njt_static.derive_njt_stop_routes(data["trips"], data["stop_times"])
    pj_trips = {
        trip_id
        for trip_id, trip in data["trips"].items()
        if "port jervis" in (trip["headsign"] or "").lower()
    }
    assert pj_trips, "the fixture must keep at least one Port Jervis trip"
    pj_stops = {
        call["stop_id"] for trip_id in pj_trips for call in data["stop_times"].get(trip_id, [])
    }
    routes_seen = {route for stop in pj_stops for route in index.get(stop, [])}
    assert routes_seen & {"5", "6"}, (
        f"Port Jervis stations must report MAIN/BERG, got {sorted(routes_seen)}"
    )
    # And no route in the feed is named for it.
    assert not [
        rid
        for rid, route in data["routes"].items()
        if "port jervis" in ((route["long_name"] or "") + (route["short_name"] or "")).lower()
    ]


@golden
def test_golden_every_trip_carries_a_train_number():
    """trip_short_name IS the train number and 15b's second join key: the probe
    measured entity.id == train number == trip_short_name at 745 of 745. A blank
    would break that join silently."""
    with _fixture_zip() as zf:
        trips = njt_static._parse_open(zf)["trips"]
    blank = [tid for tid, trip in trips.items() if not trip["short_name"]]
    assert not blank, f"{len(blank)} trips carry no trip_short_name"


@golden
def test_golden_the_committed_fixture_holds_exactly_the_trim_rule_writes():
    """PINS THE TRIM CONTRACT, and says so, because it cannot pin anything else.

    An earlier version of this test asserted that calendar.txt and feed_info.txt
    are absent and described itself as catching upstream drift. It could not:
    gen_njt_fixture.py writes a hardcoded six-file list and never copies either
    member through under any circumstances, so the assertion was true by
    construction whatever NJ Transit publishes. Deleting the generator's real drift
    check (its EXPECTED_ABSENT loop) left this green.

    UPSTREAM DRIFT IS THE GENERATOR'S JOB, and it does it against the live archive's
    own member list, which is the only place the question can be asked. What a
    committed fixture can honestly pin is the TRIM: these six members always, and
    at most one more.

    THE SEVENTH IS SPLIT ACROSS TWO ASSERTIONS ON PURPOSE (15c). shapes.txt arrives
    in its own refresh after the other six are already committed, so this test
    cannot demand it without going red for every checkout between the two commits,
    and cannot forbid it without going red the moment it lands. So this one says
    "the six, plus at most shapes.txt and nothing else", and its PRESENCE is pinned
    by the golden_shapes sentinel instead, which skips locally and FAILS in CI. A
    conditional here would have been the dormant-golden disease; a sentinel is the
    house answer to exactly this.
    """
    committed = {path.name for path in FIXTURE_DIR.iterdir() if path.suffix == ".txt"}
    required = {
        "agency.txt",
        "routes.txt",
        "stops.txt",
        "trips.txt",
        "stop_times.txt",
        "calendar_dates.txt",
    }
    assert required <= committed, (
        f"the trim rule writes these six members; the fixture is missing "
        f"{sorted(required - committed)}"
    )
    assert committed - required <= {"shapes.txt"}, (
        f"the fixture holds a member the trim rule does not write: "
        f"{sorted(committed - required - {'shapes.txt'})}"
    )


@golden
def test_golden_the_fixture_validates_against_its_own_service_window():
    """Validated with a clock inside the fixture's own span rather than the wall
    clock, so this asserts the fixture is STRUCTURALLY valid without turning red
    the day its captured schedule expires. The guard's behavior at today's edge is
    pinned by the synthetic boundary tests above, where the clock is the subject."""
    with _fixture_zip() as zf:
        data = njt_static._parse_open(zf)
        latest = njt_static.latest_service_date(data["calendar_dates"])
        assert latest is not None
        inside = datetime.strptime(latest, "%Y%m%d").replace(tzinfo=NYC_TZ).timestamp()
        njt_static.validate_njt_publication(zf, now=inside)


# ---------------------------------------------------------------------------
# Route lines against the fixture: the three claims, and their synthetic twin
# ---------------------------------------------------------------------------
#
# EACH CLAIM IS A FUNCTION, CALLED TWICE. Once by a golden over the committed
# fixture (guarded on shapes.txt, so it skips locally until the refresh lands and
# FAILS in CI), and once by a hermetic test over an archive this module builds,
# stations and all. That is what stops the goldens being written blind: the
# assertions run today, against geometry whose right answer is known by
# construction, so what the refresh adds is real data rather than the first
# execution of the code path.

# A station must sit within this distance of its own route's drawn geometry, in
# the isotropic degree basis the frontend projects in (longitude scaled by
# cos(40.7 deg); frontend/helpers.js builds the same basis at _COS_LAT).
#
# THE VALUE IS THE FRONTEND'S OWN, NOT A NEW JUDGEMENT. helpers.js sets
# RAILROAD_ROUTE_ACCEPT_DIST = 0.0025 and rejects any projection beyond it, so a
# station further from the line than this does not glide: the train falls back to
# a straight chord between stops. Asserting at exactly that number makes this
# golden the question a rider would ask ("do the stations and the track describe
# the same railroad"), and makes a fixture whose geometry would glide badly fail
# HERE rather than silently on the map.
_STATION_ON_LINE_DIST = 0.0025

# No route may draw more variants than this. The trim's most-branched routes
# reference four distinct shape_ids, so four is the ceiling its input allows: a
# route above it would mean the builder emitted geometry no trip referenced, and a
# route at it would mean four genuinely divergent branches on one line, which is
# worth a human look either way.
_MAX_ROUTE_VARIANTS = 4

# THE MEASURE IS PRODUCTION'S, imported rather than restated here (15c Part 1b).
# route_geometry.distance_to_polylines is what the dedup uses to decide whether two
# lines are the same line, and this golden uses it to decide whether a station is on
# its line. One implementation means a change to the measure moves both, instead of
# the golden quietly asserting something the app no longer does.


def _routes_with_service(parsed: dict) -> set[str]:
    """Route ids some trip actually runs. NOT routes.txt's twelve: the Meadowlands
    Rail Line (17) is published as a route and runs only for events, so a
    publication can carry it with no trips at all, and a route with no trips has no
    geometry by construction rather than by defect."""
    return {trip["route_id"] for trip in parsed["trips"].values() if trip.get("route_id")}


def _check_every_serviced_route_draws_a_line(parsed: dict) -> list[dict]:
    """CLAIM 1: every route that runs trips carries at least one polyline, and no
    route without service sneaks in. Returns the build so a caller can assert more."""
    built = njt_static.build_njt_route_shapes(parsed["trips"], parsed["shapes"], parsed["routes"])
    drawn = {entry["route"] for entry in built}
    serviced = _routes_with_service(parsed)
    assert drawn <= serviced, f"routes drawn with no service: {sorted(drawn - serviced)}"
    missing = sorted(serviced - drawn)
    assert not missing, (
        f"routes run trips but draw no line: {missing}. Every trip carries a shape_id in "
        "this feed, so a serviced route with no geometry means the shapes slice and the "
        "trips slice disagree."
    )
    for entry in built:
        assert entry["polylines"], f"route {entry['route']} is present with no polyline"
        assert all(len(p) >= 2 for p in entry["polylines"]), "a polyline needs two points to draw"
    return built


def _check_stations_sit_on_their_routes(parsed: dict) -> int:
    """CLAIM 2, and the one that says the geometry and the stations describe the
    same railroad: every station projects onto the geometry of every route that
    serves it. Returns the number of (station, route) pairs checked, so a caller
    can refuse a vacuous pass."""
    built = njt_static.build_njt_route_shapes(parsed["trips"], parsed["shapes"], parsed["routes"])
    polylines_by_route = {entry["route"]: entry["polylines"] for entry in built}
    station_routes = njt_static.derive_njt_stop_routes(parsed["trips"], parsed["stop_times"])
    measured: list[tuple[float, str]] = []
    for stop_id, route_ids in sorted(station_routes.items()):
        stop = parsed["stops"].get(stop_id)
        if stop is None:
            continue  # a stop with no usable coordinate: the parser already dropped it
        for route_id in sorted(route_ids):
            if route_id not in polylines_by_route:
                continue  # covered by claim 1, which names it there rather than here
            distance = route_geometry.distance_to_polylines(
                [stop["lat"], stop["lon"]], polylines_by_route[route_id]
            )
            measured.append((distance, f"{stop['name']} ({stop_id}) on route {route_id}"))
    assert measured, "no (station, route) pair was checked, so this asserted nothing"
    # THE WORST PAIR, NOT THE FIRST. Asserting inside the loop reported whichever
    # station came first in stop_id order, which is an arbitrary station that
    # happened to be over the line; the number a human needs is the worst one in the
    # fixture, because that is what says how much headroom the tolerance has.
    worst_distance, worst_pair = max(measured)
    assert worst_distance <= _STATION_ON_LINE_DIST, (
        f"the worst station is {worst_pair}, {worst_distance:.5f} from its route's "
        f"geometry, past the {_STATION_ON_LINE_DIST} the frontend will project within. "
        "A station that far off its own line does not glide: its trains fall back to a "
        f"straight chord. {sum(1 for d, _ in measured if d > _STATION_ON_LINE_DIST)} of "
        f"{len(measured)} pairs are over."
    )
    return len(measured)


def _check_variant_counts_are_bounded(parsed: dict) -> None:
    """CLAIM 3: the dedup demonstrably ran. Per route a bound on variants, and in
    aggregate strictly fewer polylines than referenced shapes, which is what a
    builder that kept every variant would fail."""
    built = njt_static.build_njt_route_shapes(parsed["trips"], parsed["shapes"], parsed["routes"])
    for entry in built:
        assert 1 <= len(entry["polylines"]) <= _MAX_ROUTE_VARIANTS, (
            f"route {entry['route']} draws {len(entry['polylines'])} variants, outside "
            f"1..{_MAX_ROUTE_VARIANTS}"
        )
    referenced = route_geometry.shape_ids_by_route(parsed["trips"])
    total_referenced = sum(len(ids) for ids in referenced.values())
    total_kept = sum(len(entry["polylines"]) for entry in built)
    assert total_kept < total_referenced, (
        f"{total_kept} polylines from {total_referenced} referenced shapes: nothing "
        "collapsed, so the dedup is not running. A feed publishing one shape per "
        "direction always has variants to collapse."
    )


def test_the_station_tolerance_is_the_frontends_own_number_and_not_a_local_one():
    """THE TOLERANCE IS A SEAM, so it is asserted rather than commented.

    _STATION_ON_LINE_DIST is not a judgement this file gets to make: it is
    RAILROAD_ROUTE_ACCEPT_DIST from frontend/helpers.js, the distance beyond which
    computeRouteSlice refuses a projection and the train falls back to a straight
    chord. A number written down twice drifts, and the drift here is invisible in
    both directions: loosened, this golden stops catching geometry that would glide
    badly; tightened, it fails on a fixture the map renders perfectly.

    WHAT IT DOES NOT ADD, stated because the first draft of this docstring claimed
    it and measurement said otherwise: it is NOT what makes an infinite tolerance
    fatal. 15c mutation M2 set _STATION_ON_LINE_DIST to inf and
    test_the_station_projection_claim_fails_when_a_station_leaves_its_line, which
    already existed, went red on its own (the negative control stops being able to
    fail). This test catches the OTHER direction, which nothing else could see: the
    FRONTEND'S constant moving while the golden's stays, leaving a golden that
    passes happily while asserting a distance the map no longer projects within.

    Read out of the file rather than restated, for the reason the MOBILE_MAX_WIDTH_PX
    node test reads style.css rather than trusting a comment.
    """
    helpers = (Path(__file__).resolve().parents[2] / "frontend" / "helpers.js").read_text(
        encoding="utf-8"
    )
    match = re.search(r"const RAILROAD_ROUTE_ACCEPT_DIST = ([0-9.]+);", helpers)
    assert match, "frontend/helpers.js no longer declares RAILROAD_ROUTE_ACCEPT_DIST"
    assert float(match.group(1)) == _STATION_ON_LINE_DIST, (
        f"the golden projects stations within {_STATION_ON_LINE_DIST} while the "
        f"frontend accepts {match.group(1)}: one of the two moved alone, so this "
        "golden is no longer asking the question a rider would ask"
    )


# The stations for the synthetic railway, placed ON the geometry the shapes table
# above draws: two termini, the junction the branches leave from, and one station
# deliberately offset from the track to prove the tolerance is doing work rather
# than only matching coordinates that are identical.
_GEOM_STOPS = (
    "stop_id,stop_code,stop_name,stop_lat,stop_lon\n"
    f"201,A,Trunk Origin,{_TRUNK[0][0]},{_TRUNK[0][1]}\n"
    f"202,J,Branch Junction,{_TRUNK[8][0]},{_TRUNK[8][1]}\n"
    f"203,LB,Long Branch End,{_BRANCH_A[-1][0]},{_BRANCH_A[-1][1]}\n"
    f"204,BH,Bay Head End,{_BRANCH_B[-1][0]},{_BRANCH_B[-1][1]}\n"
    # 0.002 north of the track: inside the 0.0025 the frontend projects within, so
    # this station glides, and it would stop gliding if the tolerance shrank.
    f"205,OFF,Platform Offset,{_TRUNK[4][0] + 0.002},{_TRUNK[4][1]}\n"
    "206,ML,Main Line Stop,40.90,-74.20\n"
)
_GEOM_STOP_TIMES = (
    "trip_id,arrival_time,departure_time,stop_id,stop_sequence\n"
    "T1,07:00:00,07:00:30,201,1\n"
    "T1,07:10:00,07:10:30,205,2\n"
    "T1,07:20:00,07:20:30,202,3\n"
    "T2,08:00:00,08:00:30,202,1\n"
    "T2,08:20:00,08:20:30,203,2\n"
    "T3,09:00:00,09:00:30,202,1\n"
    "T3,09:20:00,09:20:30,204,2\n"
    "T6,10:00:00,10:00:30,206,1\n"
    "T6,10:20:00,10:20:30,206,2\n"
)


# The railway drops _GEOM_TRIPS' deliberately-dangling route 13 trip. That trip
# exists to prove the PARSE tolerates a shape_id the table does not carry; claim 1
# forbids exactly that situation in a committed fixture, and both are right: a
# publication may dangle, and a fixture the goldens read may not. The generator's
# --shapes-only mode refuses rather than committing one, so the two agree.
_RAILWAY_TRIPS = "".join(
    line + "\n" for line in _GEOM_TRIPS.splitlines() if not line.startswith("13,")
)


def _railway_parsed() -> dict:
    """The synthetic railway: trips, shapes, routes, and stations standing on the
    track. Everything the three claims read, with the right answer known."""
    return _geom_parsed(
        **{
            "trips.txt": _RAILWAY_TRIPS,
            "stops.txt": _GEOM_STOPS,
            "stop_times.txt": _GEOM_STOP_TIMES,
        }
    )


def _disjoint_railway(count: int) -> dict:
    """A parsed archive where `count` mutually disjoint shapes serve one route, so
    the dedup has nothing to collapse and keeps every one of them."""
    trips = "route_id,service_id,trip_id,trip_headsign,direction_id,trip_short_name,shape_id\n"
    shapes = {}
    for i in range(count):
        trips += f"6,SVC1,D{i},Nowhere,0,90{i},d{i}\n"
        # Each line sits a whole degree from the last: no shared points anywhere.
        shapes[f"d{i}"] = [(40.0 + i, -74.0), (40.5 + i, -74.5), (41.0 + i, -75.0)]
    return _geom_parsed(**{"trips.txt": trips, "shapes.txt": _shapes_table(shapes)})


def test_the_three_line_claims_hold_on_a_synthetic_railway():
    """The goldens' code path, exercised now rather than when the fixture lands."""
    parsed = _railway_parsed()
    built = _check_every_serviced_route_draws_a_line(parsed)
    assert {entry["route"] for entry in built} == {"1", "6"}
    assert _check_stations_sit_on_their_routes(parsed) == 6
    _check_variant_counts_are_bounded(parsed)


def test_the_station_projection_claim_fails_when_a_station_leaves_its_line():
    """THE GUARD SEEN TO FIRE. Without this, claim 2 passing over real data could
    mean the check is sound or could mean it never measured anything."""
    adrift = _GEOM_STOPS.replace(
        f"205,OFF,Platform Offset,{_TRUNK[4][0] + 0.002},{_TRUNK[4][1]}",
        f"205,OFF,Platform Offset,{_TRUNK[4][0] + 0.2},{_TRUNK[4][1]}",
    )
    parsed = _geom_parsed(**{"stops.txt": adrift, "stop_times.txt": _GEOM_STOP_TIMES})
    with pytest.raises(AssertionError, match="does not glide|past the"):
        _check_stations_sit_on_their_routes(parsed)


def test_the_variant_bound_fails_when_nothing_collapses():
    """THE GUARD SEEN TO FIRE for claim 3, both arms, with data rather than a
    patched threshold: three disjoint shapes on one route give the dedup nothing to
    collapse, so the aggregate arm fires; five trip the per-route cap as well."""
    with pytest.raises(AssertionError, match="nothing collapsed"):
        _check_variant_counts_are_bounded(_disjoint_railway(3))
    with pytest.raises(AssertionError, match=f"outside 1..{_MAX_ROUTE_VARIANTS}"):
        _check_variant_counts_are_bounded(_disjoint_railway(5))


def test_the_serviced_route_claim_fails_when_a_line_loses_its_geometry():
    """THE GUARD SEEN TO FIRE for claim 1: drop the shapes a route's trips point at
    and the route runs trips with nothing to draw, which is the failure this claim
    exists to catch."""
    without_route_one = _shapes_table({"s5": [(40.90, -74.20), (40.95, -74.30), (41.00, -74.40)]})
    parsed = _geom_parsed(
        **{
            "shapes.txt": without_route_one,
            "stops.txt": _GEOM_STOPS,
            "stop_times.txt": _GEOM_STOP_TIMES,
        }
    )
    with pytest.raises(AssertionError, match="draw no line"):
        _check_every_serviced_route_draws_a_line(parsed)


@golden_shapes
def test_golden_every_nj_transit_route_with_service_draws_a_line():
    with _fixture_zip() as zf:
        parsed = njt_static._parse_open(zf)
    built = _check_every_serviced_route_draws_a_line(parsed)
    # THE TWELFTH ROUTE IS NOT A DEFECT. routes.txt carries twelve; this
    # publication's trips cover eleven, because the Meadowlands Rail Line (17)
    # runs for events and this trim caught none. Asserted BY NAME rather than as a
    # count, so a fixture that lost a real line cannot pass by arithmetic.
    assert len(parsed["routes"]) == 12
    assert "17" not in _routes_with_service(parsed), (
        "this publication now runs Meadowlands trips; the line below should draw"
    )
    assert {entry["route"] for entry in built} == _routes_with_service(parsed)
    assert len(built) == 11


@golden_shapes
def test_golden_every_nj_transit_station_sits_on_the_line_that_serves_it():
    with _fixture_zip() as zf:
        parsed = njt_static._parse_open(zf)
    # Every station of every route, so the count is a floor nobody can shrink by
    # accident: the fixture carries 164 stations across eleven serviced routes.
    assert _check_stations_sit_on_their_routes(parsed) >= 100


@golden_shapes
def test_golden_the_kept_variants_per_route_are_bounded():
    with _fixture_zip() as zf:
        parsed = njt_static._parse_open(zf)
    _check_variant_counts_are_bounded(parsed)


# The committed shapes.txt may not exceed this. MEASURED, not guessed: 29 shapes
# built to the real feed's statistics come to roughly 1,900 rows and 70 KB after
# simplification at NJT_SIMPLIFY_EPS, against 195,545 rows and 6.9 MB unsimplified.
# The ceiling sits an order of magnitude above that estimate and two below the
# unsimplified file, so it absorbs a publication digitized more finely than the
# model without ever tolerating a fixture where simplification silently stopped.
# For scale, the largest fixture in the repo before this one is the whole PATH
# shapes.txt at 216 KB.
_SHAPES_BYTE_CEILING = 750_000


@golden_shapes
def test_golden_the_committed_geometry_is_a_fixture_and_not_a_publication():
    """A 6.9 MB member is not a test fixture. This is the size half of the pair
    below: it catches the file growing back, whatever the cause, and the fixed-point
    golden catches the reason it would."""
    size = (FIXTURE_DIR / "shapes.txt").stat().st_size
    assert size <= _SHAPES_BYTE_CEILING, (
        f"shapes.txt is {size:,} bytes, over the {_SHAPES_BYTE_CEILING:,} ceiling. "
        "Either simplification stopped happening in the fixture arm, or this "
        "publication is digitized far more finely than the one the epsilon was "
        "measured against."
    )


@golden_shapes
def test_golden_every_committed_shape_is_already_simplified():
    """THE COUPLING THAT SAYS THE FIXTURE AND PRODUCTION HOLD THE SAME POINTS.

    The loader simplifies at NJT_SIMPLIFY_EPS on its way to drawing. If the
    committed geometry is a FIXED POINT of that same simplification, then what the
    goldens read and what production draws are the same points rather than two
    different reductions of the feed, and every line golden above is measuring the
    map rather than an artefact of the fixture being denser.

    ONE ASSERTION CANNOT SAY IT, SO THERE ARE TWO. Douglas-Peucker at a smaller
    epsilon retains a SUPERSET of what it retains at a larger one, so re-simplifying
    at the loader's epsilon changes nothing whenever the fixture was built at that
    epsilon OR ANY COARSER ONE. Measured on a 3,000-point shape: built at the
    epsilon, 135 points and a fixed point; at a tenth of it, 657 points and NOT a
    fixed point; unsimplified, 3,000 and not a fixed point; but built at TEN TIMES
    it, 33 points and still a perfect fixed point. So this arm catches a fixture
    denser than the loader would draw, and is blind to one already coarser.

    The second arm closes that direction: simplifying the committed geometry at
    TWICE the epsilon must actually remove points. A fixture built at the epsilon
    loses some (135 to fewer); one built at ten times it loses none, because 2x is
    still finer than what already reduced it. The pair brackets the epsilon the
    fixture was built at into [EPS, 2*EPS), which is as close as a file can be
    pinned to a constant it does not contain.
    """
    with _fixture_zip() as zf:
        parsed = njt_static._parse_open(zf)
    assert parsed["shapes"], "the fixture carries no geometry at all"
    for shape_id, points in sorted(parsed["shapes"].items()):
        again = route_geometry.simplify_polyline(points, route_geometry.NJT_SIMPLIFY_EPS)
        assert again == points, (
            f"shape {shape_id} is not a fixed point of simplification: the loader "
            f"reduces its {len(points)} committed points to {len(again)}, so the "
            "committed geometry is denser than what production draws. Re-run "
            "gen_njt_fixture.py --shapes-only."
        )

    # THE OTHER DIRECTION. In aggregate rather than per shape, because a short shape
    # can legitimately be two points at any tolerance and have nothing left to lose.
    committed = sum(len(points) for points in parsed["shapes"].values())
    coarser = sum(
        len(route_geometry.simplify_polyline(points, route_geometry.NJT_SIMPLIFY_EPS * 2))
        for points in parsed["shapes"].values()
    )
    assert coarser < committed, (
        f"doubling the tolerance removes nothing from the committed geometry "
        f"({committed} points either way), so the fixture was built at a COARSER "
        "epsilon than the loader uses and the fixed-point check above cannot see it. "
        "Re-run gen_njt_fixture.py --shapes-only."
    )


@golden_shapes
def test_golden_the_bounded_parse_reaches_every_shape_the_committed_trips_reference():
    """The PARSE half of the identity claim: whatever the fixture carries, the
    bounded read reaches exactly the shapes the trips point at. The file-level half
    (nothing committed that no trip references) is the identity replay's, in
    test_njt_fixture_trim.py, beside the rest of that replay."""
    with _fixture_zip() as zf:
        parsed = njt_static._parse_open(zf)
    referenced = {trip["shape_id"] for trip in parsed["trips"].values() if trip.get("shape_id")}
    assert referenced, "the committed trips reference no geometry at all"
    assert set(parsed["shapes"]) == referenced, (
        "the bounded parse and the committed trips disagree about which shapes exist"
    )
