"""Tests for the NJ Transit static GTFS loader (backend/njt_static.py).

Two layers, matching test_ferry_static.py's house discipline:

  - Synthetic tables (io.BytesIO and in-memory zips, no disk beyond tmp_path, no
    network) exercise the pure parsers, the validators, the derived indexes, and
    the loader's control flow. Every band and boundary is asserted at its edge.
  - Golden tests read the committed trimmed copy of the REAL feed under
    fixtures/njt_gtfs/ (generated by backend/scripts/gen_njt_fixture.py, trim rule
    documented there) and assert the live-verified facts: 12 routes all carrying
    route_type 113, the two identity stops, the west-of-Hudson stations carrying
    MAIN and BERG rather than a Port Jervis route id, and the trip_short_name
    train numbers 15b joins on. They skip loudly when the fixture has not been
    generated yet; in CI a missing fixture FAILS.

THE FIXTURE NEEDS CREDENTIALS TO GENERATE, which is new for this repo: NJ
Transit's archive is behind an account, so no CI job and no agent can produce it.
The goldens below are therefore dormant-and-loud until someone with a RailData
registration runs the generator and commits the result, which is exactly what
conftest.golden_fixture_guard is for.

THE SERVICE-DATE GUARD IS TESTED WITH AN INJECTED CLOCK, never the wall clock.
That is not merely tidiness: the guard compares against TODAY, so a wall-clock
test would pass or fail depending on the day it ran, and the one case worth
pinning (latest == today exactly, which must PASS) would be unreachable on all
but one day per fixture.
"""

from __future__ import annotations

import io
import zipfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

import njt_auth
import njt_static
from conftest import golden_fixture_guard
from feeds.shared import NYC_TZ
from static_shared import StaticValidationError

pytestmark = pytest.mark.anyio

# datetime.UTC is 3.11+; spelled this way so the module parses on the documented
# floor without depending on the alias landing in the version that runs it.
UTC = timezone.utc

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "njt_gtfs"
golden = golden_fixture_guard(
    FIXTURE_DIR / "stops.txt",
    "backend/scripts/gen_njt_fixture.py (needs NJT_USERNAME and NJT_PASSWORD)",
)

# A fixed instant with a comfortable margin from any local midnight, so the
# service-date arithmetic below is about the guard rather than about the clock:
# 2026-08-06 12:00 EDT.
NOW = datetime(2026, 8, 6, 12, 0, tzinfo=NYC_TZ).timestamp()


def _ny_date(now: float, offset_days: int) -> str:
    """YYYYMMDD in New York, `offset_days` from `now`. Built by calendar
    arithmetic on the local date rather than by adding seconds, so a DST boundary
    inside the offset cannot silently move the answer by a day."""
    day = datetime.fromtimestamp(now, NYC_TZ).date() + timedelta(days=offset_days)
    return day.strftime("%Y%m%d")


# ---------------------------------------------------------------------------
# Table builders: NJT-shaped rows, per the 2026-08-05 probe
# ---------------------------------------------------------------------------

AGENCY = (
    "agency_id,agency_name,agency_url,agency_timezone\nNJT,NJ TRANSIT,https://x,America/New_York\n"
)

# route_type 113 on every row (the GTFS extended "Rail Service" type), and an
# EMPTY route_text_color, which is what all 12 real routes carry.
ROUTES = (
    "route_id,route_short_name,route_long_name,route_type,route_color,route_text_color\n"
    "1,NEC,Northeast Corridor,113,EF3E42,\n"
    "5,BERG,Bergen County Line,113,C0C0C0,\n"
    "6,MAIN,Main Line,113,FFD700,\n"
    "13,PASC,Pascack Valley,113,A2A4A3,\n"
)

# FLAT stops: no location_type, no parent_station, no wheelchair column anywhere.
STOPS = (
    "stop_id,stop_code,stop_name,stop_lat,stop_lon\n"
    "109,NY,New York Penn Station,40.750568,-73.993519\n"
    "112,NP,Newark Penn Station,40.734924,-74.164581\n"
    "38,HB,Hoboken,40.734984,-74.027683\n"
    "125,PJ,Port Jervis,41.377300,-74.691700\n"
    "160,,No Coords,,\n"  # malformed coordinate: skipped by the parser
)

TRIPS = (
    "route_id,service_id,trip_id,trip_headsign,direction_id,trip_short_name\n"
    "1,SVC1,T1,New York,0,3800\n"
    "6,SVC1,T2,Port Jervis,1,1600\n"
    "13,SVC1,T3,Hoboken,1,1610\n"
    ",SVC1,T4,Orphan,0,9999\n"  # no route_id: contributes nothing to the routes fold
)

STOP_TIMES = (
    "trip_id,arrival_time,departure_time,stop_id,stop_sequence\n"
    "T1,07:00:00,07:00:30,112,1\n"
    "T1,07:20:00,07:20:30,109,2\n"
    "T2,23:40:00,23:41:00,38,1\n"
    "T2,25:10:00,25:11:00,125,2\n"  # past midnight: hours exceed 24, by design
    "T3,08:00:00,08:00:00,38,1\n"
    "T3,08:25:00,08:25:00,112,2\n"
    "T4,09:00:00,09:00:00,109,1\n"
)


def _calendar_dates(now: float = NOW, last_offset: int = 60, first_offset: int = -7) -> str:
    return (
        "service_id,date,exception_type\n"
        f"SVC1,{_ny_date(now, first_offset)},1\n"
        f"SVC1,{_ny_date(now, last_offset)},1\n"
    )


def _members(**overrides: str) -> dict[str, str]:
    """A valid NJT archive's members. NOTE what is absent: no calendar.txt and no
    feed_info.txt, because the real feed ships neither and a fixture that carried
    them would test a loader nobody wrote."""
    members = {
        "agency.txt": AGENCY,
        "routes.txt": ROUTES,
        "stops.txt": STOPS,
        "trips.txt": TRIPS,
        "stop_times.txt": STOP_TIMES,
        "calendar_dates.txt": _calendar_dates(),
        # Present and never parsed, exactly as upstream ships it (15a defers it).
        "shapes.txt": "shape_id,shape_pt_sequence,shape_pt_lat,shape_pt_lon\ns1,1,40.7,-74.0\n",
    }
    members.update(overrides)
    return members


def _zip_bytes(members: dict[str, str], drop: tuple[str, ...] = ()) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, body in members.items():
            if name not in drop:
                zf.writestr(name, body)
    return buf.getvalue()


def _open(members: dict[str, str], drop: tuple[str, ...] = ()) -> zipfile.ZipFile:
    return zipfile.ZipFile(io.BytesIO(_zip_bytes(members, drop)))


def _parse(table: str, parser):
    return parser(io.BytesIO(table.encode()))


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------


def test_stops_parse_flat_with_no_wheelchair_field():
    stops = _parse(STOPS, njt_static._parse_stops)
    assert set(stops) == {"109", "112", "38", "125"}  # 160 has no usable coordinate
    assert stops["109"] == {
        "id": "109",
        "name": "New York Penn Station",
        "lat": 40.750568,
        "lon": -73.993519,
    }
    # THE ABSENCE IS THE ASSERTION. FerryStop carries a wheelchair bool because the
    # ferry feed publishes one; NJ Transit publishes no accessibility data at all,
    # and a hardcoded False would read downstream as an affirmative "not
    # accessible" the feed never said.
    assert "wheelchair" not in stops["109"]


def test_routes_carry_the_extended_type_and_a_null_text_color():
    routes = _parse(ROUTES, njt_static._parse_routes)
    assert len(routes) == 4
    # route_type 113 passes through verbatim: it is the GTFS EXTENDED "Rail
    # Service" type, not one of the classic 0-7 basic types, and anything
    # switch-casing 0-7 falls through it.
    assert {r["type"] for r in routes.values()} == {"113"}
    assert routes["13"]["short_name"] == "PASC"
    # Empty on all 12 real routes, so it must arrive as None rather than "" and
    # must not be defaulted to a contrast colour by the parser.
    assert routes["13"]["text_color"] is None


def test_trips_carry_the_train_number_and_the_headsign():
    trips = _parse(TRIPS, njt_static._parse_trips)
    # short_name IS the train number and 15b's second join key (745/745 on the probe).
    assert trips["T1"]["short_name"] == "3800"
    # The ONLY place Port Jervis is named anywhere in this feed: it has no route id.
    assert trips["T2"]["headsign"] == "Port Jervis"
    assert trips["T2"]["route_id"] == "6"  # MAIN, not a Port Jervis route
    assert trips["T4"]["route_id"] is None


def test_stop_times_keep_times_and_survive_hours_past_24():
    calls = _parse(STOP_TIMES, njt_static._parse_stop_times)
    assert [c["stop_id"] for c in calls["T1"]] == ["112", "109"]
    assert calls["T1"][0]["arrival"] == 7 * 3600
    # 25:10:00 is a real GTFS time, not a malformed one: a train departing after
    # midnight belongs to the previous service day and is published past 24h.
    assert calls["T2"][1]["arrival"] == 25 * 3600 + 10 * 60


@pytest.mark.parametrize(
    ("value", "expected"),
    [
        ("00:00:00", 0),
        ("07:05:09", 7 * 3600 + 5 * 60 + 9),
        ("25:10:00", 25 * 3600 + 10 * 60),
        ("", None),
        ("   ", None),
        ("7:05", None),
        ("aa:bb:cc", None),
        ("-1:00:00", None),
    ],
)
def test_gtfs_seconds(value, expected):
    assert njt_static.gtfs_seconds(value) == expected


def test_calendar_dates_counts_only_added_rows():
    """A removal says a service does NOT run that day. Counting one toward the
    service span would let a feed whose real service ended in March pass the
    staleness guard on the strength of a cancellation published for December."""
    table = (
        "service_id,date,exception_type\n"
        "SVC1,20260801,1\n"
        "SVC1,20260802,1\n"
        "SVC1,20991231,2\n"  # a removal far in the future: must NOT extend the span
        "SVC1,2026,1\n"  # malformed date: dropped
        ",20260803,1\n"  # no service_id: dropped
    )
    dates = _parse(table, njt_static._parse_calendar_dates)
    assert dates == {"SVC1": {"20260801", "20260802"}}
    assert njt_static.latest_service_date(dates) == "20260802"


def test_latest_service_date_of_nothing_is_none():
    assert njt_static.latest_service_date({}) is None
    assert njt_static.latest_service_date({"SVC1": set()}) is None


# ---------------------------------------------------------------------------
# Validators
# ---------------------------------------------------------------------------


def test_a_calendar_dates_only_feed_validates():
    """THE HEADLINE ACCEPTANCE CASE. This feed ships no calendar.txt and no
    feed_info.txt; a validator that required either would reject every valid NJ
    Transit publication, forever, with a message about a missing member that is
    never coming."""
    with _open(_members()) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)
        njt_static.validate_njt_publication(zf, now=NOW)


# --- a feed that adopts the ordinary GTFS shape ----------------------------
#
# calendar.txt is not FORBIDDEN, only unrequired, and "not read at all" was the
# wrong answer to what happens if it appears. These three variants are the ones
# that matter, and all three used to produce a CONFIDENT WRONG ANSWER: two
# rejections whose message named the wrong cause, and one acceptance that
# published an end date 15 months early. The span is now the later of calendar's
# end_date and the latest added calendar_dates day, which gets all three right.

_CAL = "service_id,monday,tuesday,start_date,end_date\nSVC1,1,1,{start},{end}\n"


def test_a_removals_only_calendar_dates_is_fine_when_calendar_carries_the_span():
    """Variant (a). With calendar.txt present, calendar_dates is an EXCEPTION list
    again, and a feed whose only exceptions are cancellations is perfectly ordinary.
    Rejecting it as "schedules no service days" named the wrong cause entirely."""
    members = _members(
        **{
            "calendar.txt": _CAL.format(start=_ny_date(NOW, -30), end=_ny_date(NOW, 400)),
            "calendar_dates.txt": f"service_id,date,exception_type\nSVC1,{_ny_date(NOW, 120)},2\n",
        }
    )
    with _open(members) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)
    assert njt_static._service_span(_open(members)) == _ny_date(NOW, 400)


def test_a_conventional_calendar_dates_is_judged_on_calendars_end_date():
    """Variant (b). Exception-style calendar_dates whose few ADDED rows are all in
    the past, over a calendar.txt running another year. The feed schedules service
    for months; judging it on the additive rows alone rejected it as expired."""
    members = _members(
        **{
            "calendar.txt": _CAL.format(start=_ny_date(NOW, -30), end=_ny_date(NOW, 400)),
            "calendar_dates.txt": (
                f"service_id,date,exception_type\nSVC1,{_ny_date(NOW, -20)},1\n"
                f"SVC1,{_ny_date(NOW, 150)},2\n"
            ),
        }
    )
    with _open(members) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)


def test_the_span_is_the_later_of_the_two_calendars():
    """Variant (c), the quiet one. A near-future ADD plus a far-future calendar
    end_date used to be ACCEPTED while publishing the add as the feed's end date, so
    /api/status, the warmup log and the monitor's band all reported a number 15
    months early and the guard would start rejecting a healthy feed on that day."""
    members = _members(
        **{
            "calendar.txt": _CAL.format(start=_ny_date(NOW, -30), end=_ny_date(NOW, 400)),
            "calendar_dates.txt": f"service_id,date,exception_type\nSVC1,{_ny_date(NOW, 30)},1\n",
        }
    )
    assert njt_static._service_span(_open(members)) == _ny_date(NOW, 400)
    # And the other direction: calendar_dates reaching past calendar's end wins.
    members = _members(
        **{
            "calendar.txt": _CAL.format(start=_ny_date(NOW, -30), end=_ny_date(NOW, 10)),
            "calendar_dates.txt": f"service_id,date,exception_type\nSVC1,{_ny_date(NOW, 300)},1\n",
        }
    )
    assert njt_static._service_span(_open(members)) == _ny_date(NOW, 300)


def test_a_calendar_with_no_usable_end_date_contributes_nothing():
    """A calendar.txt whose end_date is blank or impossible must not rescue an
    expired feed, and must not break a healthy one either: it simply adds nothing
    and the calendar_dates answer stands."""
    for end in ("", "20261332", "not-a-date"):
        members = _members(
            **{
                "calendar.txt": _CAL.format(start=_ny_date(NOW, -30), end=end),
                "calendar_dates.txt": _calendar_dates(last_offset=-1, first_offset=-40),
            }
        )
        with _open(members) as zf:
            with pytest.raises(StaticValidationError, match="expired"):
                njt_static.validate_njt_archive(zf, now=NOW)


# --- an eight-digit string is not a date ------------------------------------


@pytest.mark.parametrize(
    "impossible", ["20261301", "20260230", "20260000", "20261232", "99999999", "00000000"]
)
def test_an_impossible_date_cannot_extend_the_service_span(impossible):
    """THE GUARD RETURNS THE HEALTHY ANSWER ON EXACTLY THE INPUT IT CANNOT READ, if
    the parser admits any eight digits. The comparison is lexicographic, so
    "20261301" (month 13) sorts above every real 2026 date: one such row anywhere in
    an 8,697-row table made a fully expired schedule look like one running into next
    year, and the monitor could not cover for it (it downgrades an unparseable date
    to WARN, and a WARN never fails a run).

    So the date is really parsed and an impossible one is dropped, exactly like a
    malformed coordinate is dropped from stops.
    """
    table = f"service_id,date,exception_type\nSVC1,{_ny_date(NOW, -400)},1\nSVC1,{impossible},1\n"
    dates = _parse(table, njt_static._parse_calendar_dates)
    assert njt_static.latest_service_date(dates) == _ny_date(NOW, -400)
    with _open(_members(**{"calendar_dates.txt": table})) as zf:
        with pytest.raises(StaticValidationError, match="expired"):
            njt_static.validate_njt_archive(zf, now=NOW)


# --- rows that are not boardable stops --------------------------------------


def test_non_boardable_rows_never_become_markers():
    """This feed is FLAT today (no location_type, no parent_station), and the parser
    assumes that. What it does NOT assume is that a row it has never seen is a stop:
    a parent station, an entrance, a generic node and a boarding area are all things
    a train does not call at, and placing them puts a station pin and a street-
    entrance pin a few metres from the platform that actually carries the routes,
    each with no routes of its own. Nothing downstream could catch that: the
    monitor's stop count is a lower bound and the identity check passes because a
    parent keeps the station's name.
    """
    table = (
        "stop_id,stop_name,stop_lat,stop_lon,location_type,parent_station\n"
        "109,New York Penn Station,40.750568,-73.993519,1,\n"  # parent station
        "109A,NY Penn Track 1,40.750568,-73.993519,0,109\n"  # boardable platform
        "109E,NY Penn 7th Ave entrance,40.750100,-73.993000,2,109\n"  # entrance
        "109N,NY Penn concourse,40.750200,-73.993100,3,109\n"  # generic node
        "112,Newark Penn Station,40.734924,-74.164581,,\n"  # today's flat shape
    )
    stops = _parse(table, njt_static._parse_stops)
    assert set(stops) == {"109A", "112"}, (
        "only boardable rows (blank or 0 location_type) may become markers"
    )


def test_shapes_may_be_absent_because_nothing_parses_it_yet():
    """15a defers shapes.txt (10 MB of the 11.1 MB payload, no consumer). It is
    deliberately not required, so a publication that dropped it still serves rather
    than trading a working map for geometry nothing reads."""
    with _open(_members(), drop=("shapes.txt",)) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)


@pytest.mark.parametrize(
    "member",
    ["agency.txt", "routes.txt", "trips.txt", "stops.txt", "stop_times.txt", "calendar_dates.txt"],
)
def test_a_missing_required_member_fails_validation(member):
    with _open(_members(), drop=(member,)) as zf:
        with pytest.raises(StaticValidationError, match=member):
            njt_static.validate_njt_archive(zf, now=NOW)


@pytest.mark.parametrize(
    ("member", "what"),
    [
        ("stops.txt", "stops"),
        ("routes.txt", "routes"),
        ("trips.txt", "trips"),
    ],
)
def test_headers_only_table_fails_the_light_validator(member, what):
    """FINDING 4, FROM BIRTH. A headers-only table is structurally perfect and
    parses cleanly to nothing; promoting one reaches "ready" with an empty map and
    nothing retrying. Three tables are gated on every load, not just stops: a feed
    with stops and no trips places markers that can never carry a train, which is
    the same silent lie one table over.

    stop_times.txt is deliberately NOT in this list; it is the expensive table and
    the publication gate owns it. See the pair of tests below, which pin both halves
    of that split."""
    headers_only = _members()[member].splitlines()[0] + "\n"
    with _open(_members(**{member: headers_only})) as zf:
        with pytest.raises(StaticValidationError, match=f"no usable {what}"):
            njt_static.validate_njt_archive(zf, now=NOW)


def test_a_headers_only_stop_times_passes_the_light_validator():
    """THE FIRST HALF OF THE SPLIT, and it is an ACCEPTANCE test on purpose.

    validate_njt_archive runs on every load of the cached archive, so it pays only
    for the three cheap tables; stop_times.txt is the one table it does not open.
    Asserting that it passes here is what makes the next test's rejection mean
    something: without this, the two validators could be identical again and nobody
    would notice.
    """
    headers_only = STOP_TIMES.splitlines()[0] + "\n"
    with _open(_members(**{"stop_times.txt": headers_only})) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)


def test_a_headers_only_stop_times_fails_the_publication_gate():
    """THE SECOND HALF. A publication may not be promoted over a working archive
    unless the REAL parse of every table the load reads succeeds, and stop_times is
    the table only this gate opens. Delete _parse_open from
    validate_njt_publication and this is what goes red."""
    headers_only = STOP_TIMES.splitlines()[0] + "\n"
    with _open(_members(**{"stop_times.txt": headers_only})) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)  # the light gate still passes
        with pytest.raises(StaticValidationError):
            njt_static.validate_njt_publication(zf, now=NOW)


def test_a_calendar_dates_with_no_added_rows_fails_validation():
    """A headers-only calendar_dates is the finding-4 shape applied to the one
    table this feed cannot degrade around: with no calendar.txt, an empty
    calendar_dates means the publication schedules nothing at all, ever."""
    with _open(_members(**{"calendar_dates.txt": "service_id,date,exception_type\n"})) as zf:
        with pytest.raises(StaticValidationError, match="schedules no service days"):
            njt_static.validate_njt_archive(zf, now=NOW)


def test_a_calendar_dates_of_removals_only_schedules_nothing():
    """Removals do not extend a service span. A table of nothing but cancellations
    (however far in the future they reach) schedules no service, and must be
    rejected rather than read as a feed running until 2099."""
    removals = "service_id,date,exception_type\nSVC1,20991231,2\nSVC1,20991230,2\n"
    with _open(_members(**{"calendar_dates.txt": removals})) as zf:
        with pytest.raises(StaticValidationError, match="schedules no service days"):
            njt_static.validate_njt_archive(zf, now=NOW)


# --- the service-date guard, at its boundary --------------------------------


def test_service_ending_today_is_still_servable():
    """THE BOUNDARY, and the one that has to be inclusive. A feed whose last
    service day is TODAY is running trains right now; rejecting it would drop a
    working system on its final morning, which is strictly worse than serving it
    and letting the monitor's WARN band (which fired 30 days ago) do its job."""
    with _open(_members(**{"calendar_dates.txt": _calendar_dates(last_offset=0)})) as zf:
        njt_static.validate_njt_archive(zf, now=NOW)


def test_service_that_ended_yesterday_is_rejected():
    """THE HARD LINE. With no feed_info.txt there is no feed_end_date to read, so
    calendar_dates IS the expiry signal. A publication that schedules nothing for
    today or any day after cannot be served from, and accepting it would replace a
    working archive with a dead calendar."""
    expired = _calendar_dates(last_offset=-1, first_offset=-40)
    with _open(_members(**{"calendar_dates.txt": expired})) as zf:
        with pytest.raises(StaticValidationError, match="expired"):
            njt_static.validate_njt_archive(zf, now=NOW)


def test_the_guard_reads_today_in_new_york_not_in_utc():
    """A GTFS service date is a local calendar day at the agency. For five hours
    every evening (four under EDT) the UTC date is already tomorrow, so a guard
    reading UTC would declare a feed whose last service day is today EXPIRED at
    20:00 local, on the last evening it is actually serving trains.

    23:30 EDT on 2026-08-06 is 03:30 UTC on 2026-08-07. A feed ending 2026-08-06
    must still validate.
    """
    late_evening = datetime(2026, 8, 6, 23, 30, tzinfo=NYC_TZ).timestamp()
    assert datetime.fromtimestamp(late_evening, UTC).strftime("%Y%m%d") == "20260807"
    table = "service_id,date,exception_type\nSVC1,20260806,1\n"
    with _open(_members(**{"calendar_dates.txt": table})) as zf:
        njt_static.validate_njt_archive(zf, now=late_evening)


def test_the_publication_validator_runs_the_real_parse():
    """Strictly stronger than the archive validator, and the difference is the whole
    point: a publication with clean stops, routes and trips but an undecodable byte
    in stop_times.txt (which the light validator never opens) would otherwise be
    promoted over the last-known-good and then discarded by the loader's residual
    arm, losing both archives.

    KEYED ON stop_times.txt, not on a table both validators read. An earlier version
    of this test corrupted trips.txt, which the LIGHT validator already parses, so
    it passed identically whether or not validate_njt_publication did anything at
    all: deleting the publication gate's extra parse could not fail it. The two
    validators were in fact equivalent at the time, and this test could not see it.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for name, body in _members().items():
            if name == "stop_times.txt":
                # Bytes that are not valid UTF-8, so the table is present and
                # structurally fine but cannot be read.
                zf.writestr(name, STOP_TIMES.encode()[:-5] + b"\xff\xfe\n")
            else:
                zf.writestr(name, body)
    with zipfile.ZipFile(io.BytesIO(buf.getvalue())) as zf:
        # The light gate passes: it does not open stop_times at all.
        njt_static.validate_njt_archive(zf, now=NOW)
        with pytest.raises(StaticValidationError):
            njt_static.validate_njt_publication(zf, now=NOW)


# ---------------------------------------------------------------------------
# Derived indexes
# ---------------------------------------------------------------------------


def _tables():
    return (
        _parse(TRIPS, njt_static._parse_trips),
        _parse(STOP_TIMES, njt_static._parse_stop_times),
    )


def test_stop_routes_folds_through_trips():
    trips, stop_times = _tables()
    index = njt_static.derive_njt_stop_routes(trips, stop_times)
    assert index["112"] == ["1", "13"]  # NEC and Pascack Valley both call there
    assert index["109"] == ["1"]  # T4 has no route_id, so it contributes nothing
    # PORT JERVIS COMES BACK AS MAIN, and that is the feed's own answer rather than
    # a bug: Port Jervis has no route id, so its stations can only report the route
    # their trips run under. Inventing one here would be a fiction.
    assert index["125"] == ["6"]


def test_the_trip_index_is_the_15b_join_target():
    trips, _ = _tables()
    index = njt_static.build_njt_trip_index(trips)
    assert index["T1"] == {"route_id": "1", "headsign": "New York", "short_name": "3800"}
    # A narrowed projection: direction_id and service_id stay in the full parsed
    # table, so what this publishes is exactly what a realtime entity needs.
    assert set(index["T1"]) == {"route_id", "headsign", "short_name"}


def test_the_stop_schedule_is_sorted_and_carries_the_train_number():
    trips, stop_times = _tables()
    schedule = njt_static.build_njt_stop_schedule(trips, stop_times)
    at_112 = schedule["112"]
    assert [call["trip_id"] for call in at_112] == ["T1", "T3"]  # 07:00 before 08:25
    assert at_112[0]["train"] == "3800"
    assert at_112[0]["route_id"] == "1"
    at_125 = schedule["125"]
    assert at_125[0]["arrival"] == 25 * 3600 + 10 * 60  # past-midnight time preserved


def test_a_call_with_no_times_sorts_last_rather_than_first():
    """float("inf"), not 0. A timeless call sorted to 0 would sit ahead of every
    real departure, which is the wrong end of the list to be wrong at."""
    stop_times = _parse(
        "trip_id,arrival_time,departure_time,stop_id,stop_sequence\n"
        "T1,,,109,1\n"
        "T1,07:00:00,07:00:00,112,2\n"
        "T3,06:00:00,06:00:00,109,1\n",
        njt_static._parse_stop_times,
    )
    trips, _ = _tables()
    schedule = njt_static.build_njt_stop_schedule(trips, stop_times)
    assert [call["trip_id"] for call in schedule["109"]] == ["T3", "T1"]


def test_the_stop_schedule_falls_back_to_departure_when_arrival_is_blank():
    stop_times = _parse(
        "trip_id,arrival_time,departure_time,stop_id,stop_sequence\n"
        "T1,,06:00:00,109,1\n"
        "T3,07:00:00,,109,1\n",
        njt_static._parse_stop_times,
    )
    trips, _ = _tables()
    schedule = njt_static.build_njt_stop_schedule(trips, stop_times)
    assert [call["trip_id"] for call in schedule["109"]] == ["T1", "T3"]


# ---------------------------------------------------------------------------
# The loader
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def _fresh_token_cache(monkeypatch):
    """A clean token cache per test. The production cache is process-wide on
    purpose (the static loader and, from 15b, the pollers must share one token),
    which makes it exactly the kind of state that leaks between tests."""
    monkeypatch.setattr(njt_auth, "TOKEN_CACHE", njt_auth.TokenCache())


def _fake_transport(zip_bytes: bytes, calls: list | None = None):
    async def transport(url, form, timeout_s):
        if calls is not None:
            calls.append((url, dict(form)))
        if url.endswith("getToken"):
            return 200, b'{"UserToken":"t1"}'
        return 200, zip_bytes

    return transport


async def test_absent_credentials_raise_before_any_disk_or_network(monkeypatch, tmp_path):
    """NOT-CONFIGURED IS A DISTINCT STATE, and it is reached before anything else
    happens: no cache read, no mint, no fetch. Collapsing it into the ordinary
    empty-dict failure would put an unconfigured deployment into a retry loop that
    can never succeed against an endpoint that would reject it anyway.

    The archive path is pointed at a file that DOES exist and is valid, so a loader
    that consulted the cache first would return data and fail this test. Serving a
    stale archive from a previous credentialed run would make /api/njt-stops answer
    while the status honestly said "not configured", which is the exact composite
    lie this codebase keeps removing.
    """
    cached = tmp_path / "gtfs_njt.zip"
    cached.write_bytes(_zip_bytes(_members()))
    monkeypatch.setattr(njt_static, "NJT_STATIC_ZIP", cached)
    monkeypatch.delenv(njt_auth.USERNAME_VAR, raising=False)
    monkeypatch.delenv(njt_auth.PASSWORD_VAR, raising=False)
    monkeypatch.setattr(njt_auth, "_httpx_post", _explodes())

    with pytest.raises(njt_auth.NjtNotConfigured):
        await njt_static.load_njt_static(now=NOW)


def _explodes():
    async def transport(url, form, timeout_s):
        raise AssertionError(f"no network is allowed here, but {url!r} was requested")

    return transport


async def test_a_good_download_parses_and_promotes(monkeypatch, tmp_path):
    monkeypatch.setenv(njt_auth.USERNAME_VAR, "rider")
    monkeypatch.setenv(njt_auth.PASSWORD_VAR, "secret")
    monkeypatch.setattr(njt_static, "NJT_STATIC_ZIP", tmp_path / "gtfs_njt.zip")
    calls: list = []
    monkeypatch.setattr(njt_auth, "_httpx_post", _fake_transport(_zip_bytes(_members()), calls))

    data = await njt_static.load_njt_static(now=NOW)

    assert set(data["stops"]) == {"109", "112", "38", "125"}
    assert len(data["routes"]) == 4
    assert njt_static.latest_service_date(data["calendar_dates"]) == _ny_date(NOW, 60)
    assert (tmp_path / "gtfs_njt.zip").exists(), "a validated publication must be promoted"
    # THE TOKEN WENT THROUGH THE DOOR. One mint, then the archive request carrying
    # the token as a FORM FIELD, which is the only shape RailData answers.
    assert [url.rsplit("/", 1)[-1] for url, _form in calls] == ["getToken", "getGTFS"]
    assert calls[1][1]["token"] == "t1"


async def test_a_bad_publication_is_rejected_and_nothing_is_promoted(monkeypatch, tmp_path):
    monkeypatch.setenv(njt_auth.USERNAME_VAR, "rider")
    monkeypatch.setenv(njt_auth.PASSWORD_VAR, "secret")
    zip_path = tmp_path / "gtfs_njt.zip"
    monkeypatch.setattr(njt_static, "NJT_STATIC_ZIP", zip_path)
    headers_only = STOPS.splitlines()[0] + "\n"
    bad = _zip_bytes(_members(**{"stops.txt": headers_only}))
    monkeypatch.setattr(njt_auth, "_httpx_post", _fake_transport(bad))

    assert await njt_static.load_njt_static(now=NOW) == {}
    assert not zip_path.exists(), "a rejected publication must never reach the cache path"


async def test_a_failed_download_keeps_serving_the_cached_archive(monkeypatch, tmp_path):
    """Serving old while new is bad, INCLUDING past MAX_AGE_DAYS: the age policy
    exists to pick up upstream's corrections, so it yields to validity rather than
    dropping a working system. The cached archive already passed the service-date
    guard, so this can never serve an expired schedule."""
    monkeypatch.setenv(njt_auth.USERNAME_VAR, "rider")
    monkeypatch.setenv(njt_auth.PASSWORD_VAR, "secret")
    zip_path = tmp_path / "gtfs_njt.zip"
    good = _zip_bytes(_members())
    zip_path.write_bytes(good)
    import os

    old = NOW - njt_static.MAX_AGE_DAYS * 86400 * 2
    os.utime(zip_path, (old, old))
    monkeypatch.setattr(njt_static, "NJT_STATIC_ZIP", zip_path)

    async def failing(url, form, timeout_s):
        if url.endswith("getToken"):
            return 200, b'{"UserToken":"t1"}'
        return 503, b"upstream down"

    monkeypatch.setattr(njt_auth, "_httpx_post", failing)

    data = await njt_static.load_njt_static(now=NOW)
    assert set(data["stops"]) == {"109", "112", "38", "125"}
    assert zip_path.read_bytes() == good, "the cached archive must be byte-untouched"


async def test_an_expired_cached_archive_is_treated_as_absent(monkeypatch, tmp_path):
    """The service-date guard runs on the CACHE too, not only on a publication. A
    cached archive whose schedule expired overnight is rejected here and
    re-downloaded, rather than being served for another MAX_AGE_DAYS because its
    mtime is fresh."""
    monkeypatch.setenv(njt_auth.USERNAME_VAR, "rider")
    monkeypatch.setenv(njt_auth.PASSWORD_VAR, "secret")
    zip_path = tmp_path / "gtfs_njt.zip"
    expired = _calendar_dates(last_offset=-1, first_offset=-40)
    zip_path.write_bytes(_zip_bytes(_members(**{"calendar_dates.txt": expired})))
    monkeypatch.setattr(njt_static, "NJT_STATIC_ZIP", zip_path)
    monkeypatch.setattr(njt_auth, "_httpx_post", _fake_transport(_zip_bytes(_members())))

    data = await njt_static.load_njt_static(now=NOW)
    # The fresh (valid) publication replaced it, which only happens if the expired
    # cache was treated as absent rather than as fresh-by-mtime.
    assert njt_static.latest_service_date(data["calendar_dates"]) == _ny_date(NOW, 60)


# ---------------------------------------------------------------------------
# Goldens, against the committed trim of the real feed
# ---------------------------------------------------------------------------


def _fixture_zip() -> zipfile.ZipFile:
    members = {
        path.name: path.read_text(encoding="utf-8")
        for path in sorted(FIXTURE_DIR.iterdir())
        if path.suffix == ".txt"
    }
    return _open(members)


@golden
def test_golden_the_fixture_carries_all_twelve_routes_at_type_113():
    with _fixture_zip() as zf:
        routes = njt_static._parse_open(zf)["routes"]
    assert len(routes) == 12, f"the probe found 12 NJT rail routes, fixture has {len(routes)}"
    assert {r["type"] for r in routes.values()} == {"113"}, (
        "all 12 routes carry the GTFS EXTENDED type 113; anything switch-casing 0-7 "
        "falls through it"
    )
    assert all(r["text_color"] is None for r in routes.values()), (
        "route_text_color is empty on all 12, so a renderer needs its own contrast fallback"
    )
    assert routes["13"]["short_name"] == "PASC", "Pascack Valley is a first-class route"


@golden
def test_golden_the_identity_stops_are_flat_and_named():
    with _fixture_zip() as zf:
        stops = njt_static._parse_open(zf)["stops"]
    assert "New York" in stops["109"]["name"]
    assert "Newark" in stops["112"]["name"]
    # FLAT: the parser produces exactly these four keys, and no wheelchair field,
    # because this feed carries no parent stations and no accessibility data.
    assert set(stops["109"]) == {"id", "name", "lat", "lon"}


# THE NINE WEST-OF-HUDSON STATIONS, BY NAME. Not a count, which is the point:
# the fixture is generated by a script that derives this set, so a count-based
# assertion would be checking the generator against itself. These names came from
# the 2026-08-05 probe and are the mandate the trim exists to satisfy.
WEST_OF_HUDSON_STATIONS = (
    "Suffern",  # the junction, and the one exclusivity alone always misses
    "Sloatsburg",
    "Tuxedo",
    "Harriman Station",
    "Salisbury Mills",
    "Campbell Hall",
    "Middletown, NY",
    "Otisville",
    "Port Jervis",
)


@golden
def test_golden_every_west_of_hudson_station_is_in_the_fixture_by_name():
    """THE MANDATE, ASSERTED WHERE NO GENERATOR CAN SATISFY IT BY ACCIDENT.

    The trim is supposed to carry the whole Port Jervis line, and it has now had
    two different bugs that silently dropped stations: a headsign-keyed trip set
    that cancelled itself to empty, and a lexicographic pick of two trips that
    could land on short-turns. Both were invisible because every check on them was
    derived from the same broken computation.

    This is the belt under those suspenders. It reads the committed fixture and
    demands nine specific station NAMES, so a future fixture that violates the
    mandate fails in CI no matter how it was produced, no matter which heuristic
    generated it, and no matter whether that heuristic thought it had succeeded.

    Names rather than stop ids because a rename is a fact worth failing on: this
    feed's ids are small integers that collide across systems, and 15a's identity
    checks are by name for the same reason.
    """
    with _fixture_zip() as zf:
        stops = njt_static._parse_open(zf)["stops"]
    present = {stop["name"] for stop in stops.values()}
    missing = [name for name in WEST_OF_HUDSON_STATIONS if name not in present]
    assert not missing, (
        f"the fixture is missing west-of-Hudson stations {missing}. The trim must keep a "
        "Port Jervis trip that serves the whole line; see njt_fixture_trim's coverage "
        "selection, which chooses trips by what they cover rather than by trip id order."
    )


@golden
def test_golden_the_west_of_hudson_stations_are_actually_served_by_a_kept_trip():
    """Present in stops.txt is not enough: the station has to be REACHABLE in the
    fixture, or the arrivals and placement goldens have a marker with no service.

    Distinct from the test above because the two fail for different reasons. A
    station can reach stops.txt on the coat-tails of some other line's trip through
    the mandated-stop top-up, which is the fallback for a genuinely unserved
    station and is deliberately allowed; what must not happen quietly is the WHOLE
    line arriving that way, with no Port Jervis trip in the fixture at all.
    """
    with _fixture_zip() as zf:
        data = njt_static._parse_open(zf)
    by_name = {stop["name"]: stop_id for stop_id, stop in data["stops"].items()}
    pj_trips = {
        trip_id
        for trip_id, trip in data["trips"].items()
        if "port jervis" in (trip["headsign"] or "").lower()
    }
    assert pj_trips, "a trip must NAME the line, or its identity is unrecoverable"
    served = {
        call["stop_id"] for trip_id in pj_trips for call in data["stop_times"].get(trip_id, [])
    }
    unserved = [
        name
        for name in WEST_OF_HUDSON_STATIONS
        if by_name.get(name) and by_name[name] not in served
    ]
    assert not unserved, (
        f"west-of-Hudson stations {unserved} are in stops.txt but no Port-Jervis-headsigned "
        "trip in the fixture calls at them, so nothing in the fixture connects them to the line"
    )


@golden
def test_golden_west_of_hudson_stations_carry_main_and_bergen_route_ids():
    """PORT JERVIS HAS NO ROUTE OF ITS OWN, and this is the assertion that keeps a
    later phase from quietly "fixing" that into a fiction. Its stations report the
    MAIN (6) and BERG (5) ids their trips run under, because those are the only
    route ids the feed gives them; the Port Jervis identity lives in trip_headsign
    and nowhere else."""
    with _fixture_zip() as zf:
        data = njt_static._parse_open(zf)
    index = njt_static.derive_njt_stop_routes(data["trips"], data["stop_times"])
    pj_trips = {
        trip_id
        for trip_id, trip in data["trips"].items()
        if "port jervis" in (trip["headsign"] or "").lower()
    }
    assert pj_trips, "the fixture must keep at least one Port Jervis trip"
    pj_stops = {
        call["stop_id"] for trip_id in pj_trips for call in data["stop_times"].get(trip_id, [])
    }
    routes_seen = {route for stop in pj_stops for route in index.get(stop, [])}
    assert routes_seen & {"5", "6"}, (
        f"Port Jervis stations must report MAIN/BERG, got {sorted(routes_seen)}"
    )
    # And no route in the feed is named for it.
    assert not [
        rid
        for rid, route in data["routes"].items()
        if "port jervis" in ((route["long_name"] or "") + (route["short_name"] or "")).lower()
    ]


@golden
def test_golden_every_trip_carries_a_train_number():
    """trip_short_name IS the train number and 15b's second join key: the probe
    measured entity.id == train number == trip_short_name at 745 of 745. A blank
    would break that join silently."""
    with _fixture_zip() as zf:
        trips = njt_static._parse_open(zf)["trips"]
    blank = [tid for tid, trip in trips.items() if not trip["short_name"]]
    assert not blank, f"{len(blank)} trips carry no trip_short_name"


@golden
def test_golden_the_committed_fixture_holds_exactly_the_trim_rule_writes():
    """PINS THE TRIM CONTRACT, and says so, because it cannot pin anything else.

    An earlier version of this test asserted that calendar.txt and feed_info.txt
    are absent and described itself as catching upstream drift. It could not:
    gen_njt_fixture.py writes a hardcoded six-file list and never copies either
    member through under any circumstances, so the assertion was true by
    construction whatever NJ Transit publishes. Deleting the generator's real drift
    check (its EXPECTED_ABSENT loop) left this green.

    UPSTREAM DRIFT IS THE GENERATOR'S JOB, and it does it against the live archive's
    own member list, which is the only place the question can be asked. What a
    committed fixture can honestly pin is the TRIM: exactly these six members, no
    more (shapes.txt is deliberately not committed, being 10 MB of geometry no phase
    reads yet) and no fewer.
    """
    committed = {path.name for path in FIXTURE_DIR.iterdir() if path.suffix == ".txt"}
    assert committed == {
        "agency.txt",
        "routes.txt",
        "stops.txt",
        "trips.txt",
        "stop_times.txt",
        "calendar_dates.txt",
    }, f"the trim rule writes six members; the fixture holds {sorted(committed)}"


@golden
def test_golden_the_fixture_validates_against_its_own_service_window():
    """Validated with a clock inside the fixture's own span rather than the wall
    clock, so this asserts the fixture is STRUCTURALLY valid without turning red
    the day its captured schedule expires. The guard's behavior at today's edge is
    pinned by the synthetic boundary tests above, where the clock is the subject."""
    with _fixture_zip() as zf:
        data = njt_static._parse_open(zf)
        latest = njt_static.latest_service_date(data["calendar_dates"])
        assert latest is not None
        inside = datetime.strptime(latest, "%Y%m%d").replace(tzinfo=NYC_TZ).timestamp()
        njt_static.validate_njt_publication(zf, now=inside)
