"""feeds: the MTA / PATH GTFS-Realtime fetch-and-decode layer, split by system.

This __init__ is a PERMANENT re-export shim, not a transitional one. Every name
feeds.py exposed before the split, public and underscore alike, is re-exported
here so all existing `import feeds` / `from feeds import X` sites, the tests that
reach `feeds.X`, and the mypy config keep working unmodified. Import stability is
the feature: new systems get their own module without churning any import site.
"""

from __future__ import annotations

from feeds.alerts import (
    _ALERT_CAUSE,
    _ALERT_EFFECT,
    ALERT_FEED_URLS,
    ALERT_RETENTION_MAX_S,
    _alert_window_status,
    _decode_alerts,
    _enum_name,
    _translated,
    fetch_service_alerts,
    merge_alert_generations,
)
from feeds.buses import (
    VEHICLE_POSITIONS_URL,
    fetch_vehicle_positions,
)
from feeds.path import (
    _PATH_DIRECTION,
    _PATH_DIRECTION_ID,
    PATH_IDENTITY_EXPIRY_GENERATIONS,
    PATH_MATCH_TOLERANCE_S,
    PATH_RT_URL,
    PATH_USER_AGENT,
    _decode_path_feed,
    _path_time_delta,
    fetch_path_trains,
    match_path_identities,
    new_path_identity_state,
)
from feeds.railroad import (
    _ANCHOR_COS_LAT,
    _DIRECTION_EPSILON,
    _NYC_ANCHOR_LAT,
    _NYC_ANCHOR_LON,
    _RAILROAD_DIRECTION,
    RAILROAD_FEED_URLS,
    RAILROAD_FRESHNESS_SYSTEMS,
    _decode_railroad_feed,
    _decode_railroad_placements,
    _decode_railroad_vehicles,
    _direction_from_progression,
    _dist_to_anchor,
    _infer_railroad_direction,
    _railroad_trip_start_ts,
    fetch_railroad_trains,
)
from feeds.shared import (
    _DROP_STOP_RELATIONSHIPS,
    _DROP_TRIP_RELATIONSHIPS,
    _RAILROAD_BASE,
    _STOP_SR,
    _TRIP_SR,
    ARRIVALS_PER_DIRECTION,
    MAX_FUTURE_FIRST_STOP_S,
    NYC_LAT_MAX,
    NYC_LAT_MIN,
    NYC_LON_MAX,
    NYC_LON_MIN,
    NYC_TZ,
    PROJECT_ROOT,
    RAILROAD_LAT_MAX,
    RAILROAD_LAT_MIN,
    RAILROAD_LON_MAX,
    RAILROAD_LON_MIN,
    TRIP_START_GRACE_S,
    _api_key,
    _header_timestamp,
    _in_nyc,
    _in_railroad_box,
    _stop_time,
    _trim_arrivals,
    _trip_start_ts,
    carry_forward_prev,
    logger,
)
from feeds.subway import (
    _SUBWAY_BASE,
    SUBWAY_FEED_URLS,
    _aggregate_feeds,
    _decode_feed,
    _decode_trains,
    _platform_direction,
    fetch_subway_trains,
)

__all__ = [
    "PROJECT_ROOT",
    "NYC_LAT_MIN",
    "NYC_LAT_MAX",
    "NYC_LON_MIN",
    "NYC_LON_MAX",
    "_in_nyc",
    "RAILROAD_LAT_MIN",
    "RAILROAD_LAT_MAX",
    "RAILROAD_LON_MIN",
    "RAILROAD_LON_MAX",
    "_in_railroad_box",
    "_RAILROAD_BASE",
    "_api_key",
    "_header_timestamp",
    "NYC_TZ",
    "TRIP_START_GRACE_S",
    "MAX_FUTURE_FIRST_STOP_S",
    "_stop_time",
    "_trip_start_ts",
    "ARRIVALS_PER_DIRECTION",
    "_trim_arrivals",
    "_TRIP_SR",
    "_STOP_SR",
    "_DROP_TRIP_RELATIONSHIPS",
    "_DROP_STOP_RELATIONSHIPS",
    "carry_forward_prev",
    "logger",
    "VEHICLE_POSITIONS_URL",
    "fetch_vehicle_positions",
    "_SUBWAY_BASE",
    "SUBWAY_FEED_URLS",
    "_platform_direction",
    "_decode_feed",
    "_decode_trains",
    "_aggregate_feeds",
    "fetch_subway_trains",
    "RAILROAD_FEED_URLS",
    "RAILROAD_FRESHNESS_SYSTEMS",
    "_decode_railroad_vehicles",
    "_RAILROAD_DIRECTION",
    "_NYC_ANCHOR_LAT",
    "_NYC_ANCHOR_LON",
    "_ANCHOR_COS_LAT",
    "_DIRECTION_EPSILON",
    "_dist_to_anchor",
    "_direction_from_progression",
    "_infer_railroad_direction",
    "_railroad_trip_start_ts",
    "_decode_railroad_feed",
    "_decode_railroad_placements",
    "fetch_railroad_trains",
    "PATH_RT_URL",
    "PATH_USER_AGENT",
    "_PATH_DIRECTION",
    "_decode_path_feed",
    "fetch_path_trains",
    "PATH_MATCH_TOLERANCE_S",
    "PATH_IDENTITY_EXPIRY_GENERATIONS",
    "_PATH_DIRECTION_ID",
    "new_path_identity_state",
    "_path_time_delta",
    "match_path_identities",
    "ALERT_FEED_URLS",
    "_ALERT_EFFECT",
    "_ALERT_CAUSE",
    "_alert_window_status",
    "_translated",
    "_enum_name",
    "_decode_alerts",
    "fetch_service_alerts",
    "ALERT_RETENTION_MAX_S",
    "merge_alert_generations",
]
